// src/utils/properties.js
// India location master compatibility layer.

export const PARTY_COUNTRY_OPTIONS = [{ value: "India", label: "India" }];

export { PRODUCT_BRAND_OPTIONS as PARTY_BRAND_OPTIONS } from "./common.properties";

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

export const DISTRICTS_BY_STATE = {
  "Andhra Pradesh": ["Alluri Sitharama Raju", "Anakapalli", "Ananthapuramu", "Annamayya", "Bapatla", "Chittoor", "Dr. B. R. Ambedkar Konaseema", "East Godavari", "Eluru", "Guntur", "Kakinada", "Krishna", "Kurnool", "Nandyal", "NTR", "Palnadu", "Parvathipuram Manyam", "Prakasam", "Sri Potti Sriramulu Nellore", "Sri Sathya Sai", "Srikakulam", "Tirupati", "Visakhapatnam", "Vizianagaram", "West Godavari", "YSR Kadapa"],
  "Arunachal Pradesh": ["Anjaw", "Bichom", "Changlang", "Dibang Valley", "East Kameng", "East Siang", "Itanagar Capital Complex", "Kamle", "Keyi Panyor", "Kra Daadi", "Kurung Kumey", "Lepa Rada", "Lohit", "Longding", "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Namsai", "Pakke Kessang", "Papum Pare", "Shi-Yomi", "Siang", "Tawang", "Tirap", "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang"],
  Assam: ["Baksa", "Bajali", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo", "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao", "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup", "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar", "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar", "Sonitpur", "South Salmara-Mankachar", "Tamulpur", "Tinsukia", "Udalguri", "West Karbi Anglong"],
  Bihar: ["Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur", "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj", "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj", "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur", "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa", "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan", "Supaul", "Vaishali", "West Champaran"],
  Chhattisgarh: ["Balod", "Baloda Bazar", "Balrampur-Ramanujganj", "Bastar", "Bemetara", "Bijapur", "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband", "Gaurela-Pendra-Marwahi", "Janjgir-Champa", "Jashpur", "Kabirdham", "Kanker", "Khairagarh-Chhuikhadan-Gandai", "Kondagaon", "Korba", "Koriya", "Mahasamund", "Manendragarh-Chirmiri-Bharatpur", "Mohla-Manpur-Ambagarh Chowki", "Mungeli", "Narayanpur", "Raigarh", "Rajnandgaon", "Sarangarh-Bilaigarh", "Sukma", "Surajpur", "Surguja", "Kawardha"],
  Goa: ["North Goa", "South Goa"],
  Gujarat: ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Chhota Udaipur", "Dahod", "Dang", "Devbhumi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar", "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad"],
  Haryana: ["Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"],
  "Himachal Pradesh": ["Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu", "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una"],
  Jharkhand: ["Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum", "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara", "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu", "Ramgarh", "Ranchi", "Sahibganj", "Seraikela Kharsawan", "Simdega", "West Singhbhum"],
  Karnataka: ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"],
  Kerala: ["Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam", "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta", "Thiruvananthapuram", "Thrissur", "Wayanad"],
  "Madhya Pradesh": ["Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat", "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur", "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna", "Gwalior", "Harda", "Indore", "Jabalpur", "Jhabua", "Katni", "Khandwa", "Khargone", "Maihar", "Mandla", "Mandsaur", "Mauganj", "Morena", "Narmadapuram", "Narsinghpur", "Neemuch", "Niwas", "Panna", "Pandhurna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna", "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri", "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha"],
  Maharashtra: ["Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", "Chandrapur", "Dhule", "Dharashiv", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", "Nandurbar", "Nashik", "Palghar", "Parbhani", "Pune", "Raigad", "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"],
  Manipur: ["Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul"],
  Meghalaya: ["East Garo Hills", "East Jaintia Hills", "East Khasi Hills", "Eastern West Khasi Hills", "North Garo Hills", "Ri-Bhoi", "South Garo Hills", "South West Garo Hills", "South West Khasi Hills", "West Garo Hills", "West Jaintia Hills", "West Khasi Hills"],
  Mizoram: ["Aizawl", "Champhai", "Hnahthial", "Khawzawl", "Kolasib", "Lawngtlai", "Lunglei", "Mamit", "Saitual", "Serchhip"],
  Nagaland: ["Chumoukedima", "Dimapur", "Kiphire", "Kohima", "Longleng", "Meluri", "Mokokchung", "Mon", "Niuland", "Noklak", "Peren", "Phek", "Shamator", "Tseminyu", "Tuensang", "Wokha", "Zunheboto"],
  Odisha: ["Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh", "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam", "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal", "Kendrapara", "Keonjhar", "Khordha", "Koraput", "Malkangiri", "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada", "Sambalpur", "Subarnapur", "Sundargarh"],
  Punjab: ["Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib", "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar", "Kapurthala", "Ludhiana", "Malerkotla", "Mansa", "Moga", "Pathankot", "Patiala", "Rupnagar", "Sahibzada Ajit Singh Nagar", "Sangrur", "Shahid Bhagat Singh Nagar", "Sri Muktsar Sahib", "Tarn Taran"],
  Rajasthan: ["Ajmer", "Alwar", "Anupgarh", "Balotra", "Banswara", "Baran", "Barmer", "Beawar", "Bharatpur", "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa", "Deeg", "Dholpur", "Didwana-Kuchamana", "Dudu", "Dungarpur", "Ganganagar", "Gangapur City", "Hanumangarh", "Jaipur", "Jaipur Rural", "Jaisalmer", "Jalore", "Jhalawar", "Jhunjhunu", "Jodhpur", "Jodhpur Rural", "Karauli", "Khairthal-Tijara", "Kota", "Kotputli-Behror", "Nagaur", "Neem Ka Thana", "Pali", "Phalodi", "Pratapgarh", "Rajsamand", "Salumbar", "Sawai Madhopur", "Shahpura", "Sikar", "Sirohi", "Tonk", "Udaipur"],
  Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi", "Pakyong", "Soreng"],
  "Tamil Nadu": ["Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore", "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai", "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai", "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi", "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli", "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Vellore", "Viluppuram", "Virudhunagar"],
  Telangana: ["Adilabad", "Bhadradri Kothagudem", "Hanamkonda", "Hyderabad", "Jagtial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal", "Kamareddy", "Karimnagar", "Khammam", "Kumuram Bheem Asifabad", "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak", "Medchal-Malkajgiri", "Mulugu", "Nagarkurnool", "Nalgonda", "Narayanpet", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla", "Rangareddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad", "Wanaparthy", "Warangal", "Yadadri Bhuvanagiri"],
  Tripura: ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  "Uttar Pradesh": ["Agra", "Aligarh", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya", "Ayodhya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur", "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor", "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah", "Etawah", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar", "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur", "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj", "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi", "Kheri", "Kushinagar", "Lalitpur", "Lucknow", "Maharajganj", "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur", "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Prayagraj", "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar", "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur", "Sonbhadra", "Sultanpur", "Unnao", "Varanasi"],
  Uttarakhand: ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
  "West Bengal": ["Alipurduar", "Bankura", "Paschim Bardhaman", "Purba Bardhaman", "Birbhum", "Cooch Behar", "Dakshin Dinajpur", "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram", "Kalimpong", "Kolkata", "Maldah", "Murshidabad", "Nadia", "North 24 Parganas", "South 24 Parganas", "Paschim Medinipur", "Purba Medinipur", "Uttar Dinajpur"],
  "Andaman and Nicobar Islands": ["Nicobars", "North and Middle Andaman", "South Andaman"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli", "Daman", "Diu"],
  Delhi: ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "Shahdara", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
  "Jammu and Kashmir": ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"]
};

// District-only compatibility lookup. Existing callers can continue using getLocalities(district).
export const LOCALITIES_BY_DISTRICT = {
  "Alluri Sitharama Raju": ["Alluri Sitharama Raju"],
  Anakapalli: ["Anakapalli"],
  Ananthapuramu: ["Ananthapuramu"],
  Annamayya: ["Annamayya"],
  Bapatla: ["Bapatla"],
  Chittoor: ["Chittoor"],
  "Dr. B. R. Ambedkar Konaseema": ["Dr. B. R. Ambedkar Konaseema"],
  "East Godavari": ["East Godavari"],
  Eluru: ["Eluru"],
  Guntur: ["Guntur", "Tenali", "Narasaraopet"],
  Kakinada: ["Kakinada", "Peddapuram", "Amalapuram"],
  Krishna: ["Krishna"],
  Kurnool: ["Kurnool", "Adoni", "Nandyal"],
  Nandyal: ["Nandyal"],
  NTR: ["NTR"],
  Palnadu: ["Palnadu"],
  "Parvathipuram Manyam": ["Parvathipuram Manyam"],
  Prakasam: ["Prakasam"],
  "Sri Potti Sriramulu Nellore": ["Sri Potti Sriramulu Nellore"],
  "Sri Sathya Sai": ["Sri Sathya Sai"],
  Srikakulam: ["Srikakulam"],
  Tirupati: ["Tirupati", "Srikalahasti", "Renigunta"],
  Visakhapatnam: ["Visakhapatnam", "Anakapalle", "Bheemunipatnam"],
  Vizianagaram: ["Vizianagaram"],
  "West Godavari": ["West Godavari"],
  "YSR Kadapa": ["YSR Kadapa"],
  Anjaw: ["Anjaw"],
  Bichom: ["Bichom"],
  Changlang: ["Changlang"],
  "Dibang Valley": ["Dibang Valley"],
  "East Kameng": ["East Kameng"],
  "East Siang": ["East Siang"],
  "Itanagar Capital Complex": ["Itanagar Capital Complex"],
  Kamle: ["Kamle"],
  "Keyi Panyor": ["Keyi Panyor"],
  "Kra Daadi": ["Kra Daadi"],
  "Kurung Kumey": ["Kurung Kumey"],
  "Lepa Rada": ["Lepa Rada"],
  Lohit: ["Lohit"],
  Longding: ["Longding"],
  "Lower Dibang Valley": ["Lower Dibang Valley"],
  "Lower Siang": ["Lower Siang"],
  "Lower Subansiri": ["Lower Subansiri"],
  Namsai: ["Namsai"],
  "Pakke Kessang": ["Pakke Kessang"],
  "Papum Pare": ["Papum Pare"],
  "Shi-Yomi": ["Shi-Yomi"],
  Siang: ["Siang"],
  Tawang: ["Tawang"],
  Tirap: ["Tirap"],
  "Upper Siang": ["Upper Siang"],
  "Upper Subansiri": ["Upper Subansiri"],
  "West Kameng": ["West Kameng"],
  "West Siang": ["West Siang"],
  Baksa: ["Baksa"],
  Bajali: ["Bajali"],
  Barpeta: ["Barpeta"],
  Biswanath: ["Biswanath"],
  Bongaigaon: ["Bongaigaon"],
  Cachar: ["Silchar", "Lakhipur"],
  Charaideo: ["Charaideo"],
  Chirang: ["Chirang"],
  Darrang: ["Darrang"],
  Dhemaji: ["Dhemaji"],
  Dhubri: ["Dhubri"],
  Dibrugarh: ["Dibrugarh", "Naharkatiya"],
  "Dima Hasao": ["Dima Hasao"],
  Goalpara: ["Goalpara"],
  Golaghat: ["Golaghat"],
  Hailakandi: ["Hailakandi"],
  Hojai: ["Hojai"],
  Jorhat: ["Jorhat", "Mariani"],
  Kamrup: ["Rangia", "Palashbari"],
  "Kamrup Metropolitan": ["Guwahati"],
  "Karbi Anglong": ["Karbi Anglong"],
  Karimganj: ["Karimganj"],
  Kokrajhar: ["Kokrajhar"],
  Lakhimpur: ["Lakhimpur"],
  Majuli: ["Majuli"],
  Morigaon: ["Morigaon"],
  Nagaon: ["Nagaon", "Hojai"],
  Nalbari: ["Nalbari"],
  Sivasagar: ["Sivasagar"],
  Sonitpur: ["Tezpur", "Dhekiajuli"],
  "South Salmara-Mankachar": ["South Salmara-Mankachar"],
  Tamulpur: ["Tamulpur"],
  Tinsukia: ["Tinsukia", "Digboi", "Doomdooma"],
  Udalguri: ["Udalguri"],
  "West Karbi Anglong": ["West Karbi Anglong"],
  Araria: ["Araria"],
  Arwal: ["Arwal"],
  Aurangabad: ["Aurangabad", "Chhatrapati Sambhajinagar", "Paithan", "Sillod"],
  Banka: ["Banka"],
  Begusarai: ["Begusarai"],
  Bhagalpur: ["Bhagalpur", "Sultanganj"],
  Bhojpur: ["Bhojpur"],
  Buxar: ["Buxar"],
  Darbhanga: ["Darbhanga", "Benipur"],
  "East Champaran": ["East Champaran"],
  Gaya: ["Gaya", "Bodh Gaya", "Sherghati"],
  Gopalganj: ["Gopalganj"],
  Jamui: ["Jamui"],
  Jehanabad: ["Jehanabad"],
  Kaimur: ["Kaimur"],
  Katihar: ["Katihar"],
  Khagaria: ["Khagaria"],
  Kishanganj: ["Kishanganj"],
  Lakhisarai: ["Lakhisarai"],
  Madhepura: ["Madhepura"],
  Madhubani: ["Madhubani"],
  Munger: ["Munger"],
  Muzaffarpur: ["Muzaffarpur", "Kanti"],
  Nalanda: ["Bihar Sharif", "Rajgir"],
  Nawada: ["Nawada"],
  Patna: ["Patna", "Danapur", "Phulwari Sharif"],
  Purnia: ["Purnia", "Banmankhi"],
  Rohtas: ["Rohtas"],
  Saharsa: ["Saharsa"],
  Samastipur: ["Samastipur"],
  Saran: ["Saran"],
  Sheikhpura: ["Sheikhpura"],
  Sheohar: ["Sheohar"],
  Sitamarhi: ["Sitamarhi"],
  Siwan: ["Siwan"],
  Supaul: ["Supaul"],
  Vaishali: ["Hajipur", "Mahua"],
  "West Champaran": ["West Champaran"],
  Balod: ["Balod"],
  "Baloda Bazar": ["Baloda Bazar"],
  "Balrampur-Ramanujganj": ["Balrampur-Ramanujganj"],
  Bastar: ["Bastar"],
  Bemetara: ["Bemetara"],
  Bijapur: ["Bijapur"],
  Bilaspur: ["Bilaspur", "Takhatpur"],
  Dantewada: ["Dantewada"],
  Dhamtari: ["Dhamtari"],
  Durg: ["Durg", "Bhilai", "Bemetara"],
  Gariaband: ["Gariaband"],
  "Gaurela-Pendra-Marwahi": ["Gaurela-Pendra-Marwahi"],
  "Janjgir-Champa": ["Janjgir-Champa"],
  Jashpur: ["Jashpur"],
  Kabirdham: ["Kabirdham"],
  Kanker: ["Kanker"],
  "Khairagarh-Chhuikhadan-Gandai": ["Khairagarh-Chhuikhadan-Gandai"],
  Kondagaon: ["Kondagaon"],
  Korba: ["Korba", "Katghora"],
  Koriya: ["Koriya"],
  Mahasamund: ["Mahasamund"],
  "Manendragarh-Chirmiri-Bharatpur": ["Manendragarh-Chirmiri-Bharatpur"],
  "Mohla-Manpur-Ambagarh Chowki": ["Mohla-Manpur-Ambagarh Chowki"],
  Mungeli: ["Mungeli"],
  Narayanpur: ["Narayanpur"],
  Raigarh: ["Raigarh", "Kharsia"],
  Rajnandgaon: ["Rajnandgaon", "Dongargarh"],
  "Sarangarh-Bilaigarh": ["Sarangarh-Bilaigarh"],
  Sukma: ["Sukma"],
  Surajpur: ["Surajpur"],
  Surguja: ["Surguja"],
  Kawardha: ["Kawardha"],
  "North Goa": ["Panaji", "Mapusa", "Ponda"],
  "South Goa": ["Margao", "Vasco da Gama", "Quepem"],
  Ahmedabad: ["Ahmedabad", "Gandhinagar"],
  Amreli: ["Amreli"],
  Anand: ["Anand"],
  Aravalli: ["Aravalli"],
  Banaskantha: ["Banaskantha"],
  Bharuch: ["Bharuch"],
  Bhavnagar: ["Bhavnagar", "Palitana", "Mahuva"],
  Botad: ["Botad"],
  "Chhota Udaipur": ["Chhota Udaipur"],
  Dahod: ["Dahod"],
  Dang: ["Dang"],
  "Devbhumi Dwarka": ["Devbhumi Dwarka"],
  Gandhinagar: ["Gandhinagar"],
  "Gir Somnath": ["Gir Somnath"],
  Jamnagar: ["Jamnagar", "Dwarka"],
  Junagadh: ["Junagadh", "Veraval", "Una"],
  Kheda: ["Kheda"],
  Kutch: ["Bhuj", "Gandhidham", "Anjar", "Mandvi"],
  Mahisagar: ["Mahisagar"],
  Mehsana: ["Mehsana"],
  Morbi: ["Morbi"],
  Narmada: ["Narmada"],
  Navsari: ["Navsari"],
  Panchmahal: ["Panchmahal"],
  Patan: ["Patan"],
  Porbandar: ["Porbandar"],
  Rajkot: ["Rajkot", "Gondal", "Morbi"],
  Sabarkantha: ["Sabarkantha"],
  Surat: ["Surat", "Bardoli", "Olpad"],
  Surendranagar: ["Surendranagar"],
  Tapi: ["Tapi"],
  Vadodara: ["Vadodara", "Dabhoi", "Padra"],
  Valsad: ["Valsad"],
  Ambala: ["Ambala", "Naraingarh"],
  Bhiwani: ["Bhiwani"],
  "Charkhi Dadri": ["Charkhi Dadri"],
  Faridabad: ["Faridabad", "Ballabhgarh"],
  Fatehabad: ["Fatehabad"],
  Gurugram: ["Gurugram", "Sohna", "Manesar"],
  Hisar: ["Hisar", "Hansi", "Barwala"],
  Jhajjar: ["Jhajjar"],
  Jind: ["Jind"],
  Kaithal: ["Kaithal"],
  Karnal: ["Karnal", "Assandh", "Nilokheri"],
  Kurukshetra: ["Kurukshetra"],
  Mahendragarh: ["Mahendragarh"],
  Nuh: ["Nuh"],
  Palwal: ["Palwal"],
  Panchkula: ["Panchkula"],
  Panipat: ["Panipat", "Samalkha"],
  Rewari: ["Rewari"],
  Rohtak: ["Rohtak"],
  Sirsa: ["Sirsa"],
  Sonipat: ["Sonipat", "Gohana", "Kundli"],
  Yamunanagar: ["Yamunanagar"],
  Chamba: ["Chamba"],
  Hamirpur: ["Hamirpur"],
  Kangra: ["Dharamshala", "Kangra", "Palampur"],
  Kinnaur: ["Kinnaur"],
  Kullu: ["Kullu", "Manali", "Bhuntar"],
  "Lahaul and Spiti": ["Lahaul and Spiti"],
  Mandi: ["Mandi", "Sundernagar"],
  Shimla: ["Shimla", "Rampur", "Theog"],
  Sirmaur: ["Sirmaur"],
  Solan: ["Solan", "Baddi", "Nalagarh"],
  Una: ["Una"],
  Bokaro: ["Bokaro", "Chas", "Phusro"],
  Chatra: ["Chatra"],
  Deoghar: ["Deoghar", "Madhupur"],
  Dhanbad: ["Dhanbad", "Sindri", "Jharia"],
  Dumka: ["Dumka"],
  "East Singhbhum": ["Jamshedpur", "Ghatsila", "Chakulia"],
  Garhwa: ["Garhwa"],
  Giridih: ["Giridih", "Dumri"],
  Godda: ["Godda"],
  Gumla: ["Gumla"],
  Hazaribagh: ["Hazaribagh", "Barhi"],
  Jamtara: ["Jamtara"],
  Khunti: ["Khunti"],
  Koderma: ["Koderma"],
  Latehar: ["Latehar"],
  Lohardaga: ["Lohardaga"],
  Pakur: ["Pakur"],
  Palamu: ["Palamu"],
  Ramgarh: ["Ramgarh"],
  Ranchi: ["Ranchi", "Bundu", "Khunti"],
  Sahibganj: ["Sahibganj"],
  "Seraikela Kharsawan": ["Seraikela Kharsawan"],
  Simdega: ["Simdega"],
  "West Singhbhum": ["West Singhbhum"],
  Bagalkot: ["Bagalkot"],
  Ballari: ["Ballari", "Hospet"],
  Belagavi: ["Belagavi", "Gokak", "Athani"],
  "Bengaluru Rural": ["Bengaluru Rural"],
  "Bengaluru Urban": ["Bengaluru", "Yelahanka", "Anekal"],
  Bidar: ["Bidar"],
  Chamarajanagar: ["Chamarajanagar"],
  Chikkaballapur: ["Chikkaballapur"],
  Chikkamagaluru: ["Chikkamagaluru", "Kadur", "Koppa"],
  Chitradurga: ["Chitradurga"],
  "Dakshina Kannada": ["Mangaluru", "Puttur", "Bantwal", "Udupi"],
  Davanagere: ["Davanagere"],
  Dharwad: ["Dharwad", "Hubballi", "Navalgund"],
  Gadag: ["Gadag"],
  Hassan: ["Hassan", "Sakleshpur", "Arasikere"],
  Haveri: ["Haveri"],
  Kalaburagi: ["Kalaburagi", "Sedam", "Chittapur"],
  Kodagu: ["Madikeri", "Virajpet", "Somwarpet"],
  Kolar: ["Kolar", "Malur", "Mulbagal"],
  Koppal: ["Koppal"],
  Mandya: ["Mandya", "Maddur", "Srirangapatna"],
  Mysuru: ["Mysuru", "Nanjangud", "Hunsur"],
  Raichur: ["Raichur"],
  Ramanagara: ["Ramanagara"],
  Shivamogga: ["Shivamogga", "Bhadravati", "Sagar"],
  Tumakuru: ["Tumakuru", "Tiptur", "Sira"],
  Udupi: ["Udupi", "Kundapura", "Karkala"],
  "Uttara Kannada": ["Karwar", "Sirsi", "Kumta", "Bhatkal"],
  Vijayapura: ["Vijayapura", "Indi", "Sindagi"],
  Yadgir: ["Yadgir"],
  Alappuzha: ["Alappuzha", "Cherthala", "Kayamkulam"],
  Ernakulam: ["Kochi", "Aluva", "Perumbavoor", "Kothamangalam"],
  Idukki: ["Painavu", "Thodupuzha", "Munnar"],
  Kannur: ["Kannur", "Thalassery", "Payyannur"],
  Kasaragod: ["Kasaragod", "Kanhangad"],
  Kollam: ["Kollam", "Karunagappally", "Kottarakkara"],
  Kottayam: ["Kottayam", "Changanassery", "Pala"],
  Kozhikode: ["Kozhikode", "Vadakara", "Koyilandy"],
  Malappuram: ["Malappuram", "Manjeri", "Tirur", "Ponnani"],
  Palakkad: ["Palakkad", "Ottapalam", "Shoranur", "Chittur"],
  Pathanamthitta: ["Pathanamthitta", "Adoor", "Thiruvalla"],
  Thiruvananthapuram: ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
  Thrissur: ["Thrissur", "Chalakudy", "Kunnamkulam", "Kodungallur"],
  Wayanad: ["Kalpetta", "Mananthavady", "Sulthan Bathery"],
  "Agar Malwa": ["Agar Malwa"],
  Alirajpur: ["Alirajpur"],
  Anuppur: ["Anuppur"],
  Ashoknagar: ["Ashoknagar"],
  Balaghat: ["Balaghat"],
  Barwani: ["Barwani"],
  Betul: ["Betul"],
  Bhind: ["Bhind"],
  Bhopal: ["Bhopal", "Berasia"],
  Burhanpur: ["Burhanpur"],
  Chhatarpur: ["Chhatarpur"],
  Chhindwara: ["Chhindwara"],
  Damoh: ["Damoh"],
  Datia: ["Datia"],
  Dewas: ["Dewas", "Sonkatch"],
  Dhar: ["Dhar"],
  Dindori: ["Dindori"],
  Guna: ["Guna"],
  Gwalior: ["Gwalior", "Dabra"],
  Harda: ["Harda"],
  Indore: ["Indore", "Mhow", "Depalpur"],
  Jabalpur: ["Jabalpur", "Sihora", "Patan"],
  Jhabua: ["Jhabua"],
  Katni: ["Katni"],
  Khandwa: ["Khandwa"],
  Khargone: ["Khargone"],
  Maihar: ["Maihar"],
  Mandla: ["Mandla"],
  Mandsaur: ["Mandsaur"],
  Mauganj: ["Mauganj"],
  Morena: ["Morena"],
  Narmadapuram: ["Narmadapuram"],
  Narsinghpur: ["Narsinghpur"],
  Neemuch: ["Neemuch"],
  Niwas: ["Niwas"],
  Panna: ["Panna"],
  Pandhurna: ["Pandhurna"],
  Raisen: ["Raisen"],
  Rajgarh: ["Rajgarh"],
  Ratlam: ["Ratlam", "Jaora"],
  Rewa: ["Rewa", "Mauganj"],
  Sagar: ["Sagar", "Bina", "Khurai"],
  Satna: ["Satna", "Maihar"],
  Sehore: ["Sehore"],
  Seoni: ["Seoni"],
  Shahdol: ["Shahdol"],
  Shajapur: ["Shajapur"],
  Sheopur: ["Sheopur"],
  Shivpuri: ["Shivpuri"],
  Sidhi: ["Sidhi"],
  Singrauli: ["Singrauli"],
  Tikamgarh: ["Tikamgarh"],
  Ujjain: ["Ujjain", "Nagda", "Mahidpur"],
  Umaria: ["Umaria"],
  Vidisha: ["Vidisha"],
  Ahmednagar: ["Ahilyanagar", "Kopargaon", "Shirdi", "Sangamner"],
  Akola: ["Akola"],
  Amravati: ["Amravati"],
  Beed: ["Beed"],
  Bhandara: ["Bhandara"],
  Buldhana: ["Buldhana"],
  Chandrapur: ["Chandrapur"],
  Dhule: ["Dhule"],
  Dharashiv: ["Dharashiv"],
  Gadchiroli: ["Gadchiroli"],
  Gondia: ["Gondia"],
  Hingoli: ["Hingoli"],
  Jalgaon: ["Jalgaon"],
  Jalna: ["Jalna"],
  Kolhapur: ["Kolhapur", "Ichalkaranji", "Gadhinglaj"],
  Latur: ["Latur"],
  "Mumbai City": ["Mumbai"],
  "Mumbai Suburban": ["Mumbai", "Andheri", "Bandra", "Borivali"],
  Nagpur: ["Nagpur", "Kamptee", "Katol"],
  Nanded: ["Nanded"],
  Nandurbar: ["Nandurbar"],
  Nashik: ["Nashik", "Malegaon", "Sinnar"],
  Palghar: ["Palghar"],
  Parbhani: ["Parbhani"],
  Pune: ["Pune", "Pimpri-Chinchwad", "Baramati", "Lonavala"],
  Raigad: ["Alibag", "Panvel", "Karjat", "Pen"],
  Ratnagiri: ["Ratnagiri"],
  Sangli: ["Sangli"],
  Satara: ["Satara"],
  Sindhudurg: ["Sindhudurg"],
  Solapur: ["Solapur"],
  Thane: ["Thane", "Kalyan", "Dombivli", "Bhiwandi"],
  Wardha: ["Wardha"],
  Washim: ["Washim"],
  Yavatmal: ["Yavatmal"],
  Bishnupur: ["Bishnupur"],
  Chandel: ["Chandel"],
  Churachandpur: ["Churachandpur"],
  "Imphal East": ["Imphal East"],
  "Imphal West": ["Imphal West"],
  Jiribam: ["Jiribam"],
  Kakching: ["Kakching"],
  Kamjong: ["Kamjong"],
  Kangpokpi: ["Kangpokpi"],
  Noney: ["Noney"],
  Pherzawl: ["Pherzawl"],
  Senapati: ["Senapati"],
  Tamenglong: ["Tamenglong"],
  Tengnoupal: ["Tengnoupal"],
  Thoubal: ["Thoubal"],
  Ukhrul: ["Ukhrul"],
  "East Garo Hills": ["East Garo Hills"],
  "East Jaintia Hills": ["East Jaintia Hills"],
  "East Khasi Hills": ["East Khasi Hills"],
  "Eastern West Khasi Hills": ["Eastern West Khasi Hills"],
  "North Garo Hills": ["North Garo Hills"],
  "Ri-Bhoi": ["Ri-Bhoi"],
  "South Garo Hills": ["South Garo Hills"],
  "South West Garo Hills": ["South West Garo Hills"],
  "South West Khasi Hills": ["South West Khasi Hills"],
  "West Garo Hills": ["West Garo Hills"],
  "West Jaintia Hills": ["West Jaintia Hills"],
  "West Khasi Hills": ["West Khasi Hills"],
  Aizawl: ["Aizawl"],
  Champhai: ["Champhai"],
  Hnahthial: ["Hnahthial"],
  Khawzawl: ["Khawzawl"],
  Kolasib: ["Kolasib"],
  Lawngtlai: ["Lawngtlai"],
  Lunglei: ["Lunglei"],
  Mamit: ["Mamit"],
  Saitual: ["Saitual"],
  Serchhip: ["Serchhip"],
  Chumoukedima: ["Chumoukedima"],
  Dimapur: ["Dimapur"],
  Kiphire: ["Kiphire"],
  Kohima: ["Kohima"],
  Longleng: ["Longleng"],
  Meluri: ["Meluri"],
  Mokokchung: ["Mokokchung"],
  Mon: ["Mon"],
  Niuland: ["Niuland"],
  Noklak: ["Noklak"],
  Peren: ["Peren"],
  Phek: ["Phek"],
  Shamator: ["Shamator"],
  Tseminyu: ["Tseminyu"],
  Tuensang: ["Tuensang"],
  Wokha: ["Wokha"],
  Zunheboto: ["Zunheboto"],
  Angul: ["Angul"],
  Balangir: ["Balangir"],
  Balasore: ["Balasore", "Jaleswar", "Soro"],
  Bargarh: ["Bargarh"],
  Bhadrak: ["Bhadrak"],
  Boudh: ["Boudh"],
  Cuttack: ["Cuttack", "Athagarh", "Choudwar"],
  Deogarh: ["Deogarh"],
  Dhenkanal: ["Dhenkanal"],
  Gajapati: ["Gajapati"],
  Ganjam: ["Berhampur", "Chhatrapur", "Bhanjanagar"],
  Jagatsinghpur: ["Jagatsinghpur"],
  Jajpur: ["Jajpur"],
  Jharsuguda: ["Jharsuguda"],
  Kalahandi: ["Kalahandi"],
  Kandhamal: ["Kandhamal"],
  Kendrapara: ["Kendrapara"],
  Keonjhar: ["Keonjhar"],
  Khordha: ["Bhubaneswar", "Khordha", "Jatni"],
  Koraput: ["Koraput"],
  Malkangiri: ["Malkangiri"],
  Mayurbhanj: ["Mayurbhanj"],
  Nabarangpur: ["Nabarangpur"],
  Nayagarh: ["Nayagarh"],
  Nuapada: ["Nuapada"],
  Puri: ["Puri", "Pipili", "Konark"],
  Rayagada: ["Rayagada"],
  Sambalpur: ["Sambalpur"],
  Subarnapur: ["Subarnapur"],
  Sundargarh: ["Rourkela", "Sundargarh", "Rajgangpur"],
  Amritsar: ["Amritsar", "Ajnala"],
  Barnala: ["Barnala"],
  Bathinda: ["Bathinda", "Rampura Phul"],
  Faridkot: ["Faridkot"],
  "Fatehgarh Sahib": ["Fatehgarh Sahib"],
  Fazilka: ["Fazilka"],
  Ferozepur: ["Ferozepur"],
  Gurdaspur: ["Gurdaspur"],
  Hoshiarpur: ["Hoshiarpur"],
  Jalandhar: ["Jalandhar", "Phillaur", "Nakodar"],
  Kapurthala: ["Kapurthala"],
  Ludhiana: ["Ludhiana", "Khanna", "Jagraon"],
  Malerkotla: ["Malerkotla"],
  Mansa: ["Mansa"],
  Moga: ["Moga"],
  Pathankot: ["Pathankot"],
  Patiala: ["Patiala", "Rajpura", "Nabha"],
  Rupnagar: ["Rupnagar"],
  "Sahibzada Ajit Singh Nagar": ["Sahibzada Ajit Singh Nagar"],
  Sangrur: ["Sangrur"],
  "Shahid Bhagat Singh Nagar": ["Shahid Bhagat Singh Nagar"],
  "Sri Muktsar Sahib": ["Sri Muktsar Sahib"],
  "Tarn Taran": ["Tarn Taran"],
  Ajmer: ["Ajmer", "Kishangarh", "Beawar"],
  Alwar: ["Alwar", "Bhiwadi", "Behror"],
  Anupgarh: ["Anupgarh"],
  Balotra: ["Balotra"],
  Banswara: ["Banswara"],
  Baran: ["Baran"],
  Barmer: ["Barmer"],
  Beawar: ["Beawar"],
  Bharatpur: ["Bharatpur", "Deeg", "Bayana"],
  Bhilwara: ["Bhilwara"],
  Bikaner: ["Bikaner", "Nokha", "Lunkaransar"],
  Bundi: ["Bundi"],
  Chittorgarh: ["Chittorgarh"],
  Churu: ["Churu"],
  Dausa: ["Dausa"],
  Deeg: ["Deeg"],
  Dholpur: ["Dholpur"],
  "Didwana-Kuchamana": ["Didwana-Kuchamana"],
  Dudu: ["Dudu"],
  Dungarpur: ["Dungarpur"],
  Ganganagar: ["Ganganagar"],
  "Gangapur City": ["Gangapur City"],
  Hanumangarh: ["Hanumangarh"],
  Jaipur: ["Jaipur", "Amer", "Chomu"],
  "Jaipur Rural": ["Jaipur Rural"],
  Jaisalmer: ["Jaisalmer"],
  Jalore: ["Jalore"],
  Jhalawar: ["Jhalawar"],
  Jhunjhunu: ["Jhunjhunu"],
  Jodhpur: ["Jodhpur", "Bilara", "Osian"],
  "Jodhpur Rural": ["Jodhpur Rural"],
  Karauli: ["Karauli"],
  "Khairthal-Tijara": ["Khairthal-Tijara"],
  Kota: ["Kota", "Ramganj Mandi", "Sangod"],
  "Kotputli-Behror": ["Kotputli-Behror"],
  Nagaur: ["Nagaur"],
  "Neem Ka Thana": ["Neem Ka Thana"],
  Pali: ["Pali"],
  Phalodi: ["Phalodi"],
  Pratapgarh: ["Pratapgarh"],
  Rajsamand: ["Rajsamand"],
  Salumbar: ["Salumbar"],
  "Sawai Madhopur": ["Sawai Madhopur"],
  Shahpura: ["Shahpura"],
  Sikar: ["Sikar"],
  Sirohi: ["Sirohi"],
  Tonk: ["Tonk"],
  Udaipur: ["Udaipur", "Gogunda", "Salumbar"],
  Gangtok: ["Gangtok"],
  Gyalshing: ["Gyalshing"],
  Mangan: ["Mangan"],
  Namchi: ["Namchi"],
  Pakyong: ["Pakyong"],
  Soreng: ["Soreng"],
  Ariyalur: ["Ariyalur", "Jayankondam", "Sendurai"],
  Chengalpattu: ["Chengalpattu", "Tambaram", "Maraimalai Nagar", "Kelambakkam"],
  Chennai: ["Chennai", "Ambattur", "Avadi", "Guindy"],
  Coimbatore: ["Coimbatore", "Pollachi", "Mettupalayam", "Sulur", "Annur", "Valparai"],
  Cuddalore: ["Cuddalore", "Chidambaram", "Panruti", "Neyveli", "Virudhachalam"],
  Dharmapuri: ["Dharmapuri", "Harur", "Pennagaram", "Palacode"],
  Dindigul: ["Dindigul", "Palani", "Kodaikanal", "Oddanchatram", "Vedasandur"],
  Erode: ["Erode", "Bhavani", "Gobichettipalayam", "Sathyamangalam", "Perundurai"],
  Kallakurichi: ["Kallakurichi", "Ulundurpet", "Sankarapuram", "Chinnasalem"],
  Kancheepuram: ["Kancheepuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
  Karur: ["Karur", "Kulithalai", "Aravakurichi"],
  Krishnagiri: ["Krishnagiri", "Hosur", "Denkanikottai"],
  Madurai: ["Madurai", "Melur", "Thirumangalam", "Usilampatti"],
  Mayiladuthurai: ["Mayiladuthurai", "Sirkazhi", "Poompuhar"],
  Nagapattinam: ["Nagapattinam", "Mayiladuthurai", "Vedaranyam"],
  Namakkal: ["Namakkal", "Tiruchengode", "Rasipuram", "Paramathi Velur"],
  Nilgiris: ["Nilgiris"],
  Perambalur: ["Perambalur", "Veppanthattai", "Kunnam"],
  Pudukkottai: ["Pudukkottai", "Aranthangi", "Alangudi", "Illuppur"],
  Ramanathapuram: ["Ramanathapuram", "Paramakudi", "Rameswaram", "Kamuthi"],
  Ranipet: ["Ranipet", "Arcot", "Walajah", "Arakkonam"],
  Salem: ["Salem", "Mettur", "Attur", "Edappadi", "Omalur", "Sankari"],
  Sivaganga: ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai"],
  Tenkasi: ["Tenkasi", "Sankarankovil", "Courtallam", "Shenkottai"],
  Thanjavur: ["Thanjavur", "Kumbakonam", "Pattukkottai", "Orathanadu"],
  Theni: ["Theni", "Periyakulam", "Bodinayakanur", "Cumbum", "Uthamapalayam", "Andipatti"],
  Thoothukudi: ["Thoothukudi"],
  Tiruchirappalli: ["Tiruchirappalli", "Srirangam", "Manapparai", "Musiri", "Thuraiyur", "Lalgudi"],
  Tirunelveli: ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Tenkasi"],
  Tirupathur: ["Tirupathur", "Vaniyambadi", "Ambur"],
  Tiruppur: ["Tiruppur", "Avinashi", "Palladam", "Dharapuram", "Kangeyam", "Udumalpet"],
  Tiruvallur: ["Tiruvallur", "Avadi", "Ponneri", "Gummidipoondi", "Tiruttani"],
  Tiruvannamalai: ["Tiruvannamalai", "Arani", "Cheyyar", "Polur"],
  Tiruvarur: ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Nannilam"],
  Vellore: ["Vellore", "Katpadi", "Gudiyatham", "Pernambut"],
  Viluppuram: ["Viluppuram"],
  Virudhunagar: ["Virudhunagar", "Sivakasi", "Rajapalayam", "Aruppukkottai", "Srivilliputhur"],
  Adilabad: ["Adilabad"],
  "Bhadradri Kothagudem": ["Bhadradri Kothagudem"],
  Hanamkonda: ["Hanamkonda"],
  Hyderabad: ["Hyderabad", "Secunderabad"],
  Jagtial: ["Jagtial"],
  Jangaon: ["Jangaon"],
  "Jayashankar Bhupalpally": ["Jayashankar Bhupalpally"],
  "Jogulamba Gadwal": ["Jogulamba Gadwal"],
  Kamareddy: ["Kamareddy"],
  Karimnagar: ["Karimnagar", "Huzurabad"],
  Khammam: ["Khammam", "Kothagudem"],
  "Kumuram Bheem Asifabad": ["Kumuram Bheem Asifabad"],
  Mahabubabad: ["Mahabubabad"],
  Mahabubnagar: ["Mahabubnagar"],
  Mancherial: ["Mancherial"],
  Medak: ["Medak"],
  "Medchal-Malkajgiri": ["Medchal", "Kompally", "Malkajgiri"],
  Mulugu: ["Mulugu"],
  Nagarkurnool: ["Nagarkurnool"],
  Nalgonda: ["Nalgonda", "Miryalaguda", "Devarakonda"],
  Narayanpet: ["Narayanpet"],
  Nirmal: ["Nirmal"],
  Nizamabad: ["Nizamabad", "Bodhan", "Armoor"],
  Peddapalli: ["Peddapalli"],
  "Rajanna Sircilla": ["Rajanna Sircilla"],
  Rangareddy: ["Hyderabad", "LB Nagar", "Shamshabad"],
  Sangareddy: ["Sangareddy"],
  Siddipet: ["Siddipet"],
  Suryapet: ["Suryapet"],
  Vikarabad: ["Vikarabad"],
  Wanaparthy: ["Wanaparthy"],
  Warangal: ["Warangal", "Hanamkonda", "Kazipet"],
  "Yadadri Bhuvanagiri": ["Yadadri Bhuvanagiri"],
  Dhalai: ["Dhalai"],
  Gomati: ["Gomati"],
  Khowai: ["Khowai"],
  "North Tripura": ["North Tripura"],
  Sepahijala: ["Sepahijala"],
  "South Tripura": ["South Tripura"],
  Unakoti: ["Unakoti"],
  "West Tripura": ["West Tripura"],
  Agra: ["Agra", "Fatehabad", "Etmadpur"],
  Aligarh: ["Aligarh"],
  "Ambedkar Nagar": ["Ambedkar Nagar"],
  Amethi: ["Amethi"],
  Amroha: ["Amroha"],
  Auraiya: ["Auraiya"],
  Ayodhya: ["Ayodhya"],
  Azamgarh: ["Azamgarh"],
  Baghpat: ["Baghpat"],
  Bahraich: ["Bahraich"],
  Ballia: ["Ballia"],
  Balrampur: ["Balrampur"],
  Banda: ["Banda"],
  Barabanki: ["Barabanki"],
  Bareilly: ["Bareilly"],
  Basti: ["Basti"],
  Bhadohi: ["Bhadohi"],
  Bijnor: ["Bijnor"],
  Budaun: ["Budaun"],
  Bulandshahr: ["Bulandshahr"],
  Chandauli: ["Chandauli"],
  Chitrakoot: ["Chitrakoot"],
  Deoria: ["Deoria"],
  Etah: ["Etah"],
  Etawah: ["Etawah"],
  Farrukhabad: ["Farrukhabad"],
  Fatehpur: ["Fatehpur"],
  Firozabad: ["Firozabad"],
  "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri"],
  Ghaziabad: ["Ghaziabad", "Loni", "Modinagar"],
  Ghazipur: ["Ghazipur"],
  Gonda: ["Gonda"],
  Gorakhpur: ["Gorakhpur", "Sahjanwa", "Pipraich"],
  Hapur: ["Hapur"],
  Hardoi: ["Hardoi"],
  Hathras: ["Hathras"],
  Jalaun: ["Jalaun"],
  Jaunpur: ["Jaunpur", "Shahganj", "Machhlishahr"],
  Jhansi: ["Jhansi"],
  Kannauj: ["Kannauj"],
  "Kanpur Dehat": ["Kanpur Dehat"],
  "Kanpur Nagar": ["Kanpur", "Bilhaur"],
  Kasganj: ["Kasganj"],
  Kaushambi: ["Kaushambi"],
  Kheri: ["Kheri"],
  Kushinagar: ["Kushinagar"],
  Lalitpur: ["Lalitpur"],
  Lucknow: ["Lucknow", "Malihabad", "Mohan"],
  Maharajganj: ["Maharajganj"],
  Mahoba: ["Mahoba"],
  Mainpuri: ["Mainpuri"],
  Mathura: ["Mathura"],
  Mau: ["Mau"],
  Meerut: ["Meerut", "Mawana", "Sardhana"],
  Mirzapur: ["Mirzapur"],
  Moradabad: ["Moradabad"],
  Muzaffarnagar: ["Muzaffarnagar"],
  Pilibhit: ["Pilibhit"],
  Prayagraj: ["Prayagraj", "Phulpur", "Koraon"],
  Raebareli: ["Raebareli"],
  Rampur: ["Rampur"],
  Saharanpur: ["Saharanpur"],
  Sambhal: ["Sambhal"],
  "Sant Kabir Nagar": ["Sant Kabir Nagar"],
  Shahjahanpur: ["Shahjahanpur"],
  Shamli: ["Shamli"],
  Shravasti: ["Shravasti"],
  Siddharthnagar: ["Siddharthnagar"],
  Sitapur: ["Sitapur"],
  Sonbhadra: ["Sonbhadra"],
  Sultanpur: ["Sultanpur"],
  Unnao: ["Unnao"],
  Varanasi: ["Varanasi", "Ramnagar", "Pindra"],
  Almora: ["Almora"],
  Bageshwar: ["Bageshwar"],
  Chamoli: ["Chamoli"],
  Champawat: ["Champawat"],
  Dehradun: ["Dehradun", "Rishikesh", "Mussoorie"],
  Haridwar: ["Haridwar", "Roorkee", "Jwalapur"],
  Nainital: ["Nainital", "Haldwani", "Ramnagar"],
  "Pauri Garhwal": ["Pauri", "Kotdwar", "Srinagar"],
  Pithoragarh: ["Pithoragarh"],
  Rudraprayag: ["Rudraprayag"],
  "Tehri Garhwal": ["Tehri Garhwal"],
  "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Kichha"],
  Uttarkashi: ["Uttarkashi"],
  Alipurduar: ["Alipurduar"],
  Bankura: ["Bankura"],
  "Paschim Bardhaman": ["Paschim Bardhaman"],
  "Purba Bardhaman": ["Purba Bardhaman"],
  Birbhum: ["Birbhum"],
  "Cooch Behar": ["Cooch Behar"],
  "Dakshin Dinajpur": ["Dakshin Dinajpur"],
  Darjeeling: ["Darjeeling", "Siliguri", "Kurseong"],
  Hooghly: ["Chinsurah", "Serampore", "Chandannagar"],
  Howrah: ["Howrah", "Uluberia"],
  Jalpaiguri: ["Jalpaiguri"],
  Jhargram: ["Jhargram"],
  Kalimpong: ["Kalimpong"],
  Kolkata: ["Kolkata"],
  Maldah: ["Maldah"],
  Murshidabad: ["Murshidabad"],
  Nadia: ["Nadia"],
  "North 24 Parganas": ["Barasat", "Barrackpore", "Bongaon"],
  "South 24 Parganas": ["Alipore", "Baruipur", "Diamond Harbour"],
  "Paschim Medinipur": ["Paschim Medinipur"],
  "Purba Medinipur": ["Purba Medinipur"],
  "Uttar Dinajpur": ["Uttar Dinajpur"],
  Nicobars: ["Car Nicobar", "Campbell Bay"],
  "North and Middle Andaman": ["Mayabunder", "Rangat"],
  "South Andaman": ["Port Blair", "Bamboo Flat"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli": ["Silvassa"],
  Daman: ["Daman"],
  Diu: ["Diu"],
  "Central Delhi": ["Central Delhi"],
  "East Delhi": ["East Delhi"],
  "New Delhi": ["New Delhi"],
  "North Delhi": ["North Delhi"],
  "North East Delhi": ["North East Delhi"],
  "North West Delhi": ["North West Delhi"],
  Shahdara: ["Shahdara"],
  "South Delhi": ["South Delhi"],
  "South East Delhi": ["South East Delhi"],
  "South West Delhi": ["South West Delhi"],
  "West Delhi": ["West Delhi"],
  Anantnag: ["Anantnag", "Bijbehara", "Pahalgam"],
  Bandipora: ["Bandipora"],
  Baramulla: ["Baramulla", "Sopore", "Uri"],
  Budgam: ["Budgam"],
  Doda: ["Doda"],
  Ganderbal: ["Ganderbal"],
  Jammu: ["Jammu", "Akhnoor", "Bishnah"],
  Kathua: ["Kathua", "Hiranagar"],
  Kishtwar: ["Kishtwar"],
  Kulgam: ["Kulgam"],
  Kupwara: ["Kupwara"],
  Poonch: ["Poonch"],
  Pulwama: ["Pulwama"],
  Rajouri: ["Rajouri"],
  Ramban: ["Ramban"],
  Reasi: ["Reasi"],
  Samba: ["Samba"],
  Shopian: ["Shopian"],
  Srinagar: ["Srinagar", "Ganderbal"],
  Udhampur: ["Udhampur", "Ramnagar"],
  Kargil: ["Kargil", "Drass"],
  Leh: ["Leh"],
  Lakshadweep: ["Kavaratti", "Agatti", "Andrott"],
  Karaikal: ["Karaikal"],
  Mahe: ["Mahe"],
  Puducherry: ["Puducherry"],
  Yanam: ["Yanam"]
};

// Preferred state-aware lookup. The key is "state|||district" so duplicate district names
// in different states cannot collide.
export const LOCALITIES_BY_STATE_AND_DISTRICT = {
  "Andhra Pradesh|||Alluri Sitharama Raju": ["Alluri Sitharama Raju"],
  "Andhra Pradesh|||Anakapalli": ["Anakapalli"],
  "Andhra Pradesh|||Ananthapuramu": ["Ananthapuramu"],
  "Andhra Pradesh|||Annamayya": ["Annamayya"],
  "Andhra Pradesh|||Bapatla": ["Bapatla"],
  "Andhra Pradesh|||Chittoor": ["Chittoor"],
  "Andhra Pradesh|||Dr. B. R. Ambedkar Konaseema": ["Dr. B. R. Ambedkar Konaseema"],
  "Andhra Pradesh|||East Godavari": ["East Godavari"],
  "Andhra Pradesh|||Eluru": ["Eluru"],
  "Andhra Pradesh|||Guntur": ["Guntur", "Tenali", "Narasaraopet"],
  "Andhra Pradesh|||Kakinada": ["Kakinada", "Peddapuram", "Amalapuram"],
  "Andhra Pradesh|||Krishna": ["Krishna"],
  "Andhra Pradesh|||Kurnool": ["Kurnool", "Adoni", "Nandyal"],
  "Andhra Pradesh|||Nandyal": ["Nandyal"],
  "Andhra Pradesh|||NTR": ["NTR"],
  "Andhra Pradesh|||Palnadu": ["Palnadu"],
  "Andhra Pradesh|||Parvathipuram Manyam": ["Parvathipuram Manyam"],
  "Andhra Pradesh|||Prakasam": ["Prakasam"],
  "Andhra Pradesh|||Sri Potti Sriramulu Nellore": ["Sri Potti Sriramulu Nellore"],
  "Andhra Pradesh|||Sri Sathya Sai": ["Sri Sathya Sai"],
  "Andhra Pradesh|||Srikakulam": ["Srikakulam"],
  "Andhra Pradesh|||Tirupati": ["Tirupati", "Srikalahasti", "Renigunta"],
  "Andhra Pradesh|||Visakhapatnam": ["Visakhapatnam", "Anakapalle", "Bheemunipatnam"],
  "Andhra Pradesh|||Vizianagaram": ["Vizianagaram"],
  "Andhra Pradesh|||West Godavari": ["West Godavari"],
  "Andhra Pradesh|||YSR Kadapa": ["YSR Kadapa"],
  "Arunachal Pradesh|||Anjaw": ["Anjaw"],
  "Arunachal Pradesh|||Bichom": ["Bichom"],
  "Arunachal Pradesh|||Changlang": ["Changlang"],
  "Arunachal Pradesh|||Dibang Valley": ["Dibang Valley"],
  "Arunachal Pradesh|||East Kameng": ["East Kameng"],
  "Arunachal Pradesh|||East Siang": ["East Siang"],
  "Arunachal Pradesh|||Itanagar Capital Complex": ["Itanagar Capital Complex"],
  "Arunachal Pradesh|||Kamle": ["Kamle"],
  "Arunachal Pradesh|||Keyi Panyor": ["Keyi Panyor"],
  "Arunachal Pradesh|||Kra Daadi": ["Kra Daadi"],
  "Arunachal Pradesh|||Kurung Kumey": ["Kurung Kumey"],
  "Arunachal Pradesh|||Lepa Rada": ["Lepa Rada"],
  "Arunachal Pradesh|||Lohit": ["Lohit"],
  "Arunachal Pradesh|||Longding": ["Longding"],
  "Arunachal Pradesh|||Lower Dibang Valley": ["Lower Dibang Valley"],
  "Arunachal Pradesh|||Lower Siang": ["Lower Siang"],
  "Arunachal Pradesh|||Lower Subansiri": ["Lower Subansiri"],
  "Arunachal Pradesh|||Namsai": ["Namsai"],
  "Arunachal Pradesh|||Pakke Kessang": ["Pakke Kessang"],
  "Arunachal Pradesh|||Papum Pare": ["Papum Pare"],
  "Arunachal Pradesh|||Shi-Yomi": ["Shi-Yomi"],
  "Arunachal Pradesh|||Siang": ["Siang"],
  "Arunachal Pradesh|||Tawang": ["Tawang"],
  "Arunachal Pradesh|||Tirap": ["Tirap"],
  "Arunachal Pradesh|||Upper Siang": ["Upper Siang"],
  "Arunachal Pradesh|||Upper Subansiri": ["Upper Subansiri"],
  "Arunachal Pradesh|||West Kameng": ["West Kameng"],
  "Arunachal Pradesh|||West Siang": ["West Siang"],
  "Assam|||Baksa": ["Baksa"],
  "Assam|||Bajali": ["Bajali"],
  "Assam|||Barpeta": ["Barpeta"],
  "Assam|||Biswanath": ["Biswanath"],
  "Assam|||Bongaigaon": ["Bongaigaon"],
  "Assam|||Cachar": ["Silchar", "Lakhipur"],
  "Assam|||Charaideo": ["Charaideo"],
  "Assam|||Chirang": ["Chirang"],
  "Assam|||Darrang": ["Darrang"],
  "Assam|||Dhemaji": ["Dhemaji"],
  "Assam|||Dhubri": ["Dhubri"],
  "Assam|||Dibrugarh": ["Dibrugarh", "Naharkatiya"],
  "Assam|||Dima Hasao": ["Dima Hasao"],
  "Assam|||Goalpara": ["Goalpara"],
  "Assam|||Golaghat": ["Golaghat"],
  "Assam|||Hailakandi": ["Hailakandi"],
  "Assam|||Hojai": ["Hojai"],
  "Assam|||Jorhat": ["Jorhat", "Mariani"],
  "Assam|||Kamrup": ["Rangia", "Palashbari"],
  "Assam|||Kamrup Metropolitan": ["Guwahati"],
  "Assam|||Karbi Anglong": ["Karbi Anglong"],
  "Assam|||Karimganj": ["Karimganj"],
  "Assam|||Kokrajhar": ["Kokrajhar"],
  "Assam|||Lakhimpur": ["Lakhimpur"],
  "Assam|||Majuli": ["Majuli"],
  "Assam|||Morigaon": ["Morigaon"],
  "Assam|||Nagaon": ["Nagaon", "Hojai"],
  "Assam|||Nalbari": ["Nalbari"],
  "Assam|||Sivasagar": ["Sivasagar"],
  "Assam|||Sonitpur": ["Tezpur", "Dhekiajuli"],
  "Assam|||South Salmara-Mankachar": ["South Salmara-Mankachar"],
  "Assam|||Tamulpur": ["Tamulpur"],
  "Assam|||Tinsukia": ["Tinsukia", "Digboi", "Doomdooma"],
  "Assam|||Udalguri": ["Udalguri"],
  "Assam|||West Karbi Anglong": ["West Karbi Anglong"],
  "Bihar|||Araria": ["Araria"],
  "Bihar|||Arwal": ["Arwal"],
  "Bihar|||Aurangabad": ["Aurangabad"],
  "Bihar|||Banka": ["Banka"],
  "Bihar|||Begusarai": ["Begusarai"],
  "Bihar|||Bhagalpur": ["Bhagalpur", "Sultanganj"],
  "Bihar|||Bhojpur": ["Bhojpur"],
  "Bihar|||Buxar": ["Buxar"],
  "Bihar|||Darbhanga": ["Darbhanga", "Benipur"],
  "Bihar|||East Champaran": ["East Champaran"],
  "Bihar|||Gaya": ["Gaya", "Bodh Gaya", "Sherghati"],
  "Bihar|||Gopalganj": ["Gopalganj"],
  "Bihar|||Jamui": ["Jamui"],
  "Bihar|||Jehanabad": ["Jehanabad"],
  "Bihar|||Kaimur": ["Kaimur"],
  "Bihar|||Katihar": ["Katihar"],
  "Bihar|||Khagaria": ["Khagaria"],
  "Bihar|||Kishanganj": ["Kishanganj"],
  "Bihar|||Lakhisarai": ["Lakhisarai"],
  "Bihar|||Madhepura": ["Madhepura"],
  "Bihar|||Madhubani": ["Madhubani"],
  "Bihar|||Munger": ["Munger"],
  "Bihar|||Muzaffarpur": ["Muzaffarpur", "Kanti"],
  "Bihar|||Nalanda": ["Bihar Sharif", "Rajgir"],
  "Bihar|||Nawada": ["Nawada"],
  "Bihar|||Patna": ["Patna", "Danapur", "Phulwari Sharif"],
  "Bihar|||Purnia": ["Purnia", "Banmankhi"],
  "Bihar|||Rohtas": ["Rohtas"],
  "Bihar|||Saharsa": ["Saharsa"],
  "Bihar|||Samastipur": ["Samastipur"],
  "Bihar|||Saran": ["Saran"],
  "Bihar|||Sheikhpura": ["Sheikhpura"],
  "Bihar|||Sheohar": ["Sheohar"],
  "Bihar|||Sitamarhi": ["Sitamarhi"],
  "Bihar|||Siwan": ["Siwan"],
  "Bihar|||Supaul": ["Supaul"],
  "Bihar|||Vaishali": ["Hajipur", "Mahua"],
  "Bihar|||West Champaran": ["West Champaran"],
  "Chhattisgarh|||Balod": ["Balod"],
  "Chhattisgarh|||Baloda Bazar": ["Baloda Bazar"],
  "Chhattisgarh|||Balrampur-Ramanujganj": ["Balrampur-Ramanujganj"],
  "Chhattisgarh|||Bastar": ["Bastar"],
  "Chhattisgarh|||Bemetara": ["Bemetara"],
  "Chhattisgarh|||Bijapur": ["Bijapur"],
  "Chhattisgarh|||Bilaspur": ["Bilaspur", "Takhatpur"],
  "Chhattisgarh|||Dantewada": ["Dantewada"],
  "Chhattisgarh|||Dhamtari": ["Dhamtari"],
  "Chhattisgarh|||Durg": ["Durg", "Bhilai", "Bemetara"],
  "Chhattisgarh|||Gariaband": ["Gariaband"],
  "Chhattisgarh|||Gaurela-Pendra-Marwahi": ["Gaurela-Pendra-Marwahi"],
  "Chhattisgarh|||Janjgir-Champa": ["Janjgir-Champa"],
  "Chhattisgarh|||Jashpur": ["Jashpur"],
  "Chhattisgarh|||Kabirdham": ["Kabirdham"],
  "Chhattisgarh|||Kanker": ["Kanker"],
  "Chhattisgarh|||Khairagarh-Chhuikhadan-Gandai": ["Khairagarh-Chhuikhadan-Gandai"],
  "Chhattisgarh|||Kondagaon": ["Kondagaon"],
  "Chhattisgarh|||Korba": ["Korba", "Katghora"],
  "Chhattisgarh|||Koriya": ["Koriya"],
  "Chhattisgarh|||Mahasamund": ["Mahasamund"],
  "Chhattisgarh|||Manendragarh-Chirmiri-Bharatpur": ["Manendragarh-Chirmiri-Bharatpur"],
  "Chhattisgarh|||Mohla-Manpur-Ambagarh Chowki": ["Mohla-Manpur-Ambagarh Chowki"],
  "Chhattisgarh|||Mungeli": ["Mungeli"],
  "Chhattisgarh|||Narayanpur": ["Narayanpur"],
  "Chhattisgarh|||Raigarh": ["Raigarh", "Kharsia"],
  "Chhattisgarh|||Rajnandgaon": ["Rajnandgaon", "Dongargarh"],
  "Chhattisgarh|||Sarangarh-Bilaigarh": ["Sarangarh-Bilaigarh"],
  "Chhattisgarh|||Sukma": ["Sukma"],
  "Chhattisgarh|||Surajpur": ["Surajpur"],
  "Chhattisgarh|||Surguja": ["Surguja"],
  "Chhattisgarh|||Kawardha": ["Kawardha"],
  "Goa|||North Goa": ["Panaji", "Mapusa", "Ponda"],
  "Goa|||South Goa": ["Margao", "Vasco da Gama", "Quepem"],
  "Gujarat|||Ahmedabad": ["Ahmedabad", "Gandhinagar"],
  "Gujarat|||Amreli": ["Amreli"],
  "Gujarat|||Anand": ["Anand"],
  "Gujarat|||Aravalli": ["Aravalli"],
  "Gujarat|||Banaskantha": ["Banaskantha"],
  "Gujarat|||Bharuch": ["Bharuch"],
  "Gujarat|||Bhavnagar": ["Bhavnagar", "Palitana", "Mahuva"],
  "Gujarat|||Botad": ["Botad"],
  "Gujarat|||Chhota Udaipur": ["Chhota Udaipur"],
  "Gujarat|||Dahod": ["Dahod"],
  "Gujarat|||Dang": ["Dang"],
  "Gujarat|||Devbhumi Dwarka": ["Devbhumi Dwarka"],
  "Gujarat|||Gandhinagar": ["Gandhinagar"],
  "Gujarat|||Gir Somnath": ["Gir Somnath"],
  "Gujarat|||Jamnagar": ["Jamnagar", "Dwarka"],
  "Gujarat|||Junagadh": ["Junagadh", "Veraval", "Una"],
  "Gujarat|||Kheda": ["Kheda"],
  "Gujarat|||Kutch": ["Bhuj", "Gandhidham", "Anjar", "Mandvi"],
  "Gujarat|||Mahisagar": ["Mahisagar"],
  "Gujarat|||Mehsana": ["Mehsana"],
  "Gujarat|||Morbi": ["Morbi"],
  "Gujarat|||Narmada": ["Narmada"],
  "Gujarat|||Navsari": ["Navsari"],
  "Gujarat|||Panchmahal": ["Panchmahal"],
  "Gujarat|||Patan": ["Patan"],
  "Gujarat|||Porbandar": ["Porbandar"],
  "Gujarat|||Rajkot": ["Rajkot", "Gondal", "Morbi"],
  "Gujarat|||Sabarkantha": ["Sabarkantha"],
  "Gujarat|||Surat": ["Surat", "Bardoli", "Olpad"],
  "Gujarat|||Surendranagar": ["Surendranagar"],
  "Gujarat|||Tapi": ["Tapi"],
  "Gujarat|||Vadodara": ["Vadodara", "Dabhoi", "Padra"],
  "Gujarat|||Valsad": ["Valsad"],
  "Haryana|||Ambala": ["Ambala", "Naraingarh"],
  "Haryana|||Bhiwani": ["Bhiwani"],
  "Haryana|||Charkhi Dadri": ["Charkhi Dadri"],
  "Haryana|||Faridabad": ["Faridabad", "Ballabhgarh"],
  "Haryana|||Fatehabad": ["Fatehabad"],
  "Haryana|||Gurugram": ["Gurugram", "Sohna", "Manesar"],
  "Haryana|||Hisar": ["Hisar", "Hansi", "Barwala"],
  "Haryana|||Jhajjar": ["Jhajjar"],
  "Haryana|||Jind": ["Jind"],
  "Haryana|||Kaithal": ["Kaithal"],
  "Haryana|||Karnal": ["Karnal", "Assandh", "Nilokheri"],
  "Haryana|||Kurukshetra": ["Kurukshetra"],
  "Haryana|||Mahendragarh": ["Mahendragarh"],
  "Haryana|||Nuh": ["Nuh"],
  "Haryana|||Palwal": ["Palwal"],
  "Haryana|||Panchkula": ["Panchkula"],
  "Haryana|||Panipat": ["Panipat", "Samalkha"],
  "Haryana|||Rewari": ["Rewari"],
  "Haryana|||Rohtak": ["Rohtak"],
  "Haryana|||Sirsa": ["Sirsa"],
  "Haryana|||Sonipat": ["Sonipat", "Gohana", "Kundli"],
  "Haryana|||Yamunanagar": ["Yamunanagar"],
  "Himachal Pradesh|||Bilaspur": ["Bilaspur"],
  "Himachal Pradesh|||Chamba": ["Chamba"],
  "Himachal Pradesh|||Hamirpur": ["Hamirpur"],
  "Himachal Pradesh|||Kangra": ["Dharamshala", "Kangra", "Palampur"],
  "Himachal Pradesh|||Kinnaur": ["Kinnaur"],
  "Himachal Pradesh|||Kullu": ["Kullu", "Manali", "Bhuntar"],
  "Himachal Pradesh|||Lahaul and Spiti": ["Lahaul and Spiti"],
  "Himachal Pradesh|||Mandi": ["Mandi", "Sundernagar"],
  "Himachal Pradesh|||Shimla": ["Shimla", "Rampur", "Theog"],
  "Himachal Pradesh|||Sirmaur": ["Sirmaur"],
  "Himachal Pradesh|||Solan": ["Solan", "Baddi", "Nalagarh"],
  "Himachal Pradesh|||Una": ["Una"],
  "Jharkhand|||Bokaro": ["Bokaro", "Chas", "Phusro"],
  "Jharkhand|||Chatra": ["Chatra"],
  "Jharkhand|||Deoghar": ["Deoghar", "Madhupur"],
  "Jharkhand|||Dhanbad": ["Dhanbad", "Sindri", "Jharia"],
  "Jharkhand|||Dumka": ["Dumka"],
  "Jharkhand|||East Singhbhum": ["Jamshedpur", "Ghatsila", "Chakulia"],
  "Jharkhand|||Garhwa": ["Garhwa"],
  "Jharkhand|||Giridih": ["Giridih", "Dumri"],
  "Jharkhand|||Godda": ["Godda"],
  "Jharkhand|||Gumla": ["Gumla"],
  "Jharkhand|||Hazaribagh": ["Hazaribagh", "Barhi"],
  "Jharkhand|||Jamtara": ["Jamtara"],
  "Jharkhand|||Khunti": ["Khunti"],
  "Jharkhand|||Koderma": ["Koderma"],
  "Jharkhand|||Latehar": ["Latehar"],
  "Jharkhand|||Lohardaga": ["Lohardaga"],
  "Jharkhand|||Pakur": ["Pakur"],
  "Jharkhand|||Palamu": ["Palamu"],
  "Jharkhand|||Ramgarh": ["Ramgarh"],
  "Jharkhand|||Ranchi": ["Ranchi", "Bundu", "Khunti"],
  "Jharkhand|||Sahibganj": ["Sahibganj"],
  "Jharkhand|||Seraikela Kharsawan": ["Seraikela Kharsawan"],
  "Jharkhand|||Simdega": ["Simdega"],
  "Jharkhand|||West Singhbhum": ["West Singhbhum"],
  "Karnataka|||Bagalkot": ["Bagalkot"],
  "Karnataka|||Ballari": ["Ballari", "Hospet"],
  "Karnataka|||Belagavi": ["Belagavi", "Gokak", "Athani"],
  "Karnataka|||Bengaluru Rural": ["Bengaluru Rural"],
  "Karnataka|||Bengaluru Urban": ["Bengaluru", "Yelahanka", "Anekal"],
  "Karnataka|||Bidar": ["Bidar"],
  "Karnataka|||Chamarajanagar": ["Chamarajanagar"],
  "Karnataka|||Chikkaballapur": ["Chikkaballapur"],
  "Karnataka|||Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Koppa"],
  "Karnataka|||Chitradurga": ["Chitradurga"],
  "Karnataka|||Dakshina Kannada": ["Mangaluru", "Puttur", "Bantwal", "Udupi"],
  "Karnataka|||Davanagere": ["Davanagere"],
  "Karnataka|||Dharwad": ["Dharwad", "Hubballi", "Navalgund"],
  "Karnataka|||Gadag": ["Gadag"],
  "Karnataka|||Hassan": ["Hassan", "Sakleshpur", "Arasikere"],
  "Karnataka|||Haveri": ["Haveri"],
  "Karnataka|||Kalaburagi": ["Kalaburagi", "Sedam", "Chittapur"],
  "Karnataka|||Kodagu": ["Madikeri", "Virajpet", "Somwarpet"],
  "Karnataka|||Kolar": ["Kolar", "Malur", "Mulbagal"],
  "Karnataka|||Koppal": ["Koppal"],
  "Karnataka|||Mandya": ["Mandya", "Maddur", "Srirangapatna"],
  "Karnataka|||Mysuru": ["Mysuru", "Nanjangud", "Hunsur"],
  "Karnataka|||Raichur": ["Raichur"],
  "Karnataka|||Ramanagara": ["Ramanagara"],
  "Karnataka|||Shivamogga": ["Shivamogga", "Bhadravati", "Sagar"],
  "Karnataka|||Tumakuru": ["Tumakuru", "Tiptur", "Sira"],
  "Karnataka|||Udupi": ["Udupi", "Kundapura", "Karkala"],
  "Karnataka|||Uttara Kannada": ["Karwar", "Sirsi", "Kumta", "Bhatkal"],
  "Karnataka|||Vijayapura": ["Vijayapura", "Indi", "Sindagi"],
  "Karnataka|||Yadgir": ["Yadgir"],
  "Kerala|||Alappuzha": ["Alappuzha", "Cherthala", "Kayamkulam"],
  "Kerala|||Ernakulam": ["Kochi", "Aluva", "Perumbavoor", "Kothamangalam"],
  "Kerala|||Idukki": ["Painavu", "Thodupuzha", "Munnar"],
  "Kerala|||Kannur": ["Kannur", "Thalassery", "Payyannur"],
  "Kerala|||Kasaragod": ["Kasaragod", "Kanhangad"],
  "Kerala|||Kollam": ["Kollam", "Karunagappally", "Kottarakkara"],
  "Kerala|||Kottayam": ["Kottayam", "Changanassery", "Pala"],
  "Kerala|||Kozhikode": ["Kozhikode", "Vadakara", "Koyilandy"],
  "Kerala|||Malappuram": ["Malappuram", "Manjeri", "Tirur", "Ponnani"],
  "Kerala|||Palakkad": ["Palakkad", "Ottapalam", "Shoranur", "Chittur"],
  "Kerala|||Pathanamthitta": ["Pathanamthitta", "Adoor", "Thiruvalla"],
  "Kerala|||Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Attingal"],
  "Kerala|||Thrissur": ["Thrissur", "Chalakudy", "Kunnamkulam", "Kodungallur"],
  "Kerala|||Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery"],
  "Madhya Pradesh|||Agar Malwa": ["Agar Malwa"],
  "Madhya Pradesh|||Alirajpur": ["Alirajpur"],
  "Madhya Pradesh|||Anuppur": ["Anuppur"],
  "Madhya Pradesh|||Ashoknagar": ["Ashoknagar"],
  "Madhya Pradesh|||Balaghat": ["Balaghat"],
  "Madhya Pradesh|||Barwani": ["Barwani"],
  "Madhya Pradesh|||Betul": ["Betul"],
  "Madhya Pradesh|||Bhind": ["Bhind"],
  "Madhya Pradesh|||Bhopal": ["Bhopal", "Berasia"],
  "Madhya Pradesh|||Burhanpur": ["Burhanpur"],
  "Madhya Pradesh|||Chhatarpur": ["Chhatarpur"],
  "Madhya Pradesh|||Chhindwara": ["Chhindwara"],
  "Madhya Pradesh|||Damoh": ["Damoh"],
  "Madhya Pradesh|||Datia": ["Datia"],
  "Madhya Pradesh|||Dewas": ["Dewas", "Sonkatch"],
  "Madhya Pradesh|||Dhar": ["Dhar"],
  "Madhya Pradesh|||Dindori": ["Dindori"],
  "Madhya Pradesh|||Guna": ["Guna"],
  "Madhya Pradesh|||Gwalior": ["Gwalior", "Dabra"],
  "Madhya Pradesh|||Harda": ["Harda"],
  "Madhya Pradesh|||Indore": ["Indore", "Mhow", "Depalpur"],
  "Madhya Pradesh|||Jabalpur": ["Jabalpur", "Sihora", "Patan"],
  "Madhya Pradesh|||Jhabua": ["Jhabua"],
  "Madhya Pradesh|||Katni": ["Katni"],
  "Madhya Pradesh|||Khandwa": ["Khandwa"],
  "Madhya Pradesh|||Khargone": ["Khargone"],
  "Madhya Pradesh|||Maihar": ["Maihar"],
  "Madhya Pradesh|||Mandla": ["Mandla"],
  "Madhya Pradesh|||Mandsaur": ["Mandsaur"],
  "Madhya Pradesh|||Mauganj": ["Mauganj"],
  "Madhya Pradesh|||Morena": ["Morena"],
  "Madhya Pradesh|||Narmadapuram": ["Narmadapuram"],
  "Madhya Pradesh|||Narsinghpur": ["Narsinghpur"],
  "Madhya Pradesh|||Neemuch": ["Neemuch"],
  "Madhya Pradesh|||Niwas": ["Niwas"],
  "Madhya Pradesh|||Panna": ["Panna"],
  "Madhya Pradesh|||Pandhurna": ["Pandhurna"],
  "Madhya Pradesh|||Raisen": ["Raisen"],
  "Madhya Pradesh|||Rajgarh": ["Rajgarh"],
  "Madhya Pradesh|||Ratlam": ["Ratlam", "Jaora"],
  "Madhya Pradesh|||Rewa": ["Rewa", "Mauganj"],
  "Madhya Pradesh|||Sagar": ["Sagar", "Bina", "Khurai"],
  "Madhya Pradesh|||Satna": ["Satna", "Maihar"],
  "Madhya Pradesh|||Sehore": ["Sehore"],
  "Madhya Pradesh|||Seoni": ["Seoni"],
  "Madhya Pradesh|||Shahdol": ["Shahdol"],
  "Madhya Pradesh|||Shajapur": ["Shajapur"],
  "Madhya Pradesh|||Sheopur": ["Sheopur"],
  "Madhya Pradesh|||Shivpuri": ["Shivpuri"],
  "Madhya Pradesh|||Sidhi": ["Sidhi"],
  "Madhya Pradesh|||Singrauli": ["Singrauli"],
  "Madhya Pradesh|||Tikamgarh": ["Tikamgarh"],
  "Madhya Pradesh|||Ujjain": ["Ujjain", "Nagda", "Mahidpur"],
  "Madhya Pradesh|||Umaria": ["Umaria"],
  "Madhya Pradesh|||Vidisha": ["Vidisha"],
  "Maharashtra|||Ahmednagar": ["Ahilyanagar", "Kopargaon", "Shirdi", "Sangamner"],
  "Maharashtra|||Akola": ["Akola"],
  "Maharashtra|||Amravati": ["Amravati"],
  "Maharashtra|||Aurangabad": ["Chhatrapati Sambhajinagar", "Paithan", "Sillod"],
  "Maharashtra|||Beed": ["Beed"],
  "Maharashtra|||Bhandara": ["Bhandara"],
  "Maharashtra|||Buldhana": ["Buldhana"],
  "Maharashtra|||Chandrapur": ["Chandrapur"],
  "Maharashtra|||Dhule": ["Dhule"],
  "Maharashtra|||Dharashiv": ["Dharashiv"],
  "Maharashtra|||Gadchiroli": ["Gadchiroli"],
  "Maharashtra|||Gondia": ["Gondia"],
  "Maharashtra|||Hingoli": ["Hingoli"],
  "Maharashtra|||Jalgaon": ["Jalgaon"],
  "Maharashtra|||Jalna": ["Jalna"],
  "Maharashtra|||Kolhapur": ["Kolhapur", "Ichalkaranji", "Gadhinglaj"],
  "Maharashtra|||Latur": ["Latur"],
  "Maharashtra|||Mumbai City": ["Mumbai"],
  "Maharashtra|||Mumbai Suburban": ["Mumbai", "Andheri", "Bandra", "Borivali"],
  "Maharashtra|||Nagpur": ["Nagpur", "Kamptee", "Katol"],
  "Maharashtra|||Nanded": ["Nanded"],
  "Maharashtra|||Nandurbar": ["Nandurbar"],
  "Maharashtra|||Nashik": ["Nashik", "Malegaon", "Sinnar"],
  "Maharashtra|||Palghar": ["Palghar"],
  "Maharashtra|||Parbhani": ["Parbhani"],
  "Maharashtra|||Pune": ["Pune", "Pimpri-Chinchwad", "Baramati", "Lonavala"],
  "Maharashtra|||Raigad": ["Alibag", "Panvel", "Karjat", "Pen"],
  "Maharashtra|||Ratnagiri": ["Ratnagiri"],
  "Maharashtra|||Sangli": ["Sangli"],
  "Maharashtra|||Satara": ["Satara"],
  "Maharashtra|||Sindhudurg": ["Sindhudurg"],
  "Maharashtra|||Solapur": ["Solapur"],
  "Maharashtra|||Thane": ["Thane", "Kalyan", "Dombivli", "Bhiwandi"],
  "Maharashtra|||Wardha": ["Wardha"],
  "Maharashtra|||Washim": ["Washim"],
  "Maharashtra|||Yavatmal": ["Yavatmal"],
  "Manipur|||Bishnupur": ["Bishnupur"],
  "Manipur|||Chandel": ["Chandel"],
  "Manipur|||Churachandpur": ["Churachandpur"],
  "Manipur|||Imphal East": ["Imphal East"],
  "Manipur|||Imphal West": ["Imphal West"],
  "Manipur|||Jiribam": ["Jiribam"],
  "Manipur|||Kakching": ["Kakching"],
  "Manipur|||Kamjong": ["Kamjong"],
  "Manipur|||Kangpokpi": ["Kangpokpi"],
  "Manipur|||Noney": ["Noney"],
  "Manipur|||Pherzawl": ["Pherzawl"],
  "Manipur|||Senapati": ["Senapati"],
  "Manipur|||Tamenglong": ["Tamenglong"],
  "Manipur|||Tengnoupal": ["Tengnoupal"],
  "Manipur|||Thoubal": ["Thoubal"],
  "Manipur|||Ukhrul": ["Ukhrul"],
  "Meghalaya|||East Garo Hills": ["East Garo Hills"],
  "Meghalaya|||East Jaintia Hills": ["East Jaintia Hills"],
  "Meghalaya|||East Khasi Hills": ["East Khasi Hills"],
  "Meghalaya|||Eastern West Khasi Hills": ["Eastern West Khasi Hills"],
  "Meghalaya|||North Garo Hills": ["North Garo Hills"],
  "Meghalaya|||Ri-Bhoi": ["Ri-Bhoi"],
  "Meghalaya|||South Garo Hills": ["South Garo Hills"],
  "Meghalaya|||South West Garo Hills": ["South West Garo Hills"],
  "Meghalaya|||South West Khasi Hills": ["South West Khasi Hills"],
  "Meghalaya|||West Garo Hills": ["West Garo Hills"],
  "Meghalaya|||West Jaintia Hills": ["West Jaintia Hills"],
  "Meghalaya|||West Khasi Hills": ["West Khasi Hills"],
  "Mizoram|||Aizawl": ["Aizawl"],
  "Mizoram|||Champhai": ["Champhai"],
  "Mizoram|||Hnahthial": ["Hnahthial"],
  "Mizoram|||Khawzawl": ["Khawzawl"],
  "Mizoram|||Kolasib": ["Kolasib"],
  "Mizoram|||Lawngtlai": ["Lawngtlai"],
  "Mizoram|||Lunglei": ["Lunglei"],
  "Mizoram|||Mamit": ["Mamit"],
  "Mizoram|||Saitual": ["Saitual"],
  "Mizoram|||Serchhip": ["Serchhip"],
  "Nagaland|||Chumoukedima": ["Chumoukedima"],
  "Nagaland|||Dimapur": ["Dimapur"],
  "Nagaland|||Kiphire": ["Kiphire"],
  "Nagaland|||Kohima": ["Kohima"],
  "Nagaland|||Longleng": ["Longleng"],
  "Nagaland|||Meluri": ["Meluri"],
  "Nagaland|||Mokokchung": ["Mokokchung"],
  "Nagaland|||Mon": ["Mon"],
  "Nagaland|||Niuland": ["Niuland"],
  "Nagaland|||Noklak": ["Noklak"],
  "Nagaland|||Peren": ["Peren"],
  "Nagaland|||Phek": ["Phek"],
  "Nagaland|||Shamator": ["Shamator"],
  "Nagaland|||Tseminyu": ["Tseminyu"],
  "Nagaland|||Tuensang": ["Tuensang"],
  "Nagaland|||Wokha": ["Wokha"],
  "Nagaland|||Zunheboto": ["Zunheboto"],
  "Odisha|||Angul": ["Angul"],
  "Odisha|||Balangir": ["Balangir"],
  "Odisha|||Balasore": ["Balasore", "Jaleswar", "Soro"],
  "Odisha|||Bargarh": ["Bargarh"],
  "Odisha|||Bhadrak": ["Bhadrak"],
  "Odisha|||Boudh": ["Boudh"],
  "Odisha|||Cuttack": ["Cuttack", "Athagarh", "Choudwar"],
  "Odisha|||Deogarh": ["Deogarh"],
  "Odisha|||Dhenkanal": ["Dhenkanal"],
  "Odisha|||Gajapati": ["Gajapati"],
  "Odisha|||Ganjam": ["Berhampur", "Chhatrapur", "Bhanjanagar"],
  "Odisha|||Jagatsinghpur": ["Jagatsinghpur"],
  "Odisha|||Jajpur": ["Jajpur"],
  "Odisha|||Jharsuguda": ["Jharsuguda"],
  "Odisha|||Kalahandi": ["Kalahandi"],
  "Odisha|||Kandhamal": ["Kandhamal"],
  "Odisha|||Kendrapara": ["Kendrapara"],
  "Odisha|||Keonjhar": ["Keonjhar"],
  "Odisha|||Khordha": ["Bhubaneswar", "Khordha", "Jatni"],
  "Odisha|||Koraput": ["Koraput"],
  "Odisha|||Malkangiri": ["Malkangiri"],
  "Odisha|||Mayurbhanj": ["Mayurbhanj"],
  "Odisha|||Nabarangpur": ["Nabarangpur"],
  "Odisha|||Nayagarh": ["Nayagarh"],
  "Odisha|||Nuapada": ["Nuapada"],
  "Odisha|||Puri": ["Puri", "Pipili", "Konark"],
  "Odisha|||Rayagada": ["Rayagada"],
  "Odisha|||Sambalpur": ["Sambalpur"],
  "Odisha|||Subarnapur": ["Subarnapur"],
  "Odisha|||Sundargarh": ["Rourkela", "Sundargarh", "Rajgangpur"],
  "Punjab|||Amritsar": ["Amritsar", "Ajnala"],
  "Punjab|||Barnala": ["Barnala"],
  "Punjab|||Bathinda": ["Bathinda", "Rampura Phul"],
  "Punjab|||Faridkot": ["Faridkot"],
  "Punjab|||Fatehgarh Sahib": ["Fatehgarh Sahib"],
  "Punjab|||Fazilka": ["Fazilka"],
  "Punjab|||Ferozepur": ["Ferozepur"],
  "Punjab|||Gurdaspur": ["Gurdaspur"],
  "Punjab|||Hoshiarpur": ["Hoshiarpur"],
  "Punjab|||Jalandhar": ["Jalandhar", "Phillaur", "Nakodar"],
  "Punjab|||Kapurthala": ["Kapurthala"],
  "Punjab|||Ludhiana": ["Ludhiana", "Khanna", "Jagraon"],
  "Punjab|||Malerkotla": ["Malerkotla"],
  "Punjab|||Mansa": ["Mansa"],
  "Punjab|||Moga": ["Moga"],
  "Punjab|||Pathankot": ["Pathankot"],
  "Punjab|||Patiala": ["Patiala", "Rajpura", "Nabha"],
  "Punjab|||Rupnagar": ["Rupnagar"],
  "Punjab|||Sahibzada Ajit Singh Nagar": ["Sahibzada Ajit Singh Nagar"],
  "Punjab|||Sangrur": ["Sangrur"],
  "Punjab|||Shahid Bhagat Singh Nagar": ["Shahid Bhagat Singh Nagar"],
  "Punjab|||Sri Muktsar Sahib": ["Sri Muktsar Sahib"],
  "Punjab|||Tarn Taran": ["Tarn Taran"],
  "Rajasthan|||Ajmer": ["Ajmer", "Kishangarh", "Beawar"],
  "Rajasthan|||Alwar": ["Alwar", "Bhiwadi", "Behror"],
  "Rajasthan|||Anupgarh": ["Anupgarh"],
  "Rajasthan|||Balotra": ["Balotra"],
  "Rajasthan|||Banswara": ["Banswara"],
  "Rajasthan|||Baran": ["Baran"],
  "Rajasthan|||Barmer": ["Barmer"],
  "Rajasthan|||Beawar": ["Beawar"],
  "Rajasthan|||Bharatpur": ["Bharatpur", "Deeg", "Bayana"],
  "Rajasthan|||Bhilwara": ["Bhilwara"],
  "Rajasthan|||Bikaner": ["Bikaner", "Nokha", "Lunkaransar"],
  "Rajasthan|||Bundi": ["Bundi"],
  "Rajasthan|||Chittorgarh": ["Chittorgarh"],
  "Rajasthan|||Churu": ["Churu"],
  "Rajasthan|||Dausa": ["Dausa"],
  "Rajasthan|||Deeg": ["Deeg"],
  "Rajasthan|||Dholpur": ["Dholpur"],
  "Rajasthan|||Didwana-Kuchamana": ["Didwana-Kuchamana"],
  "Rajasthan|||Dudu": ["Dudu"],
  "Rajasthan|||Dungarpur": ["Dungarpur"],
  "Rajasthan|||Ganganagar": ["Ganganagar"],
  "Rajasthan|||Gangapur City": ["Gangapur City"],
  "Rajasthan|||Hanumangarh": ["Hanumangarh"],
  "Rajasthan|||Jaipur": ["Jaipur", "Amer", "Chomu"],
  "Rajasthan|||Jaipur Rural": ["Jaipur Rural"],
  "Rajasthan|||Jaisalmer": ["Jaisalmer"],
  "Rajasthan|||Jalore": ["Jalore"],
  "Rajasthan|||Jhalawar": ["Jhalawar"],
  "Rajasthan|||Jhunjhunu": ["Jhunjhunu"],
  "Rajasthan|||Jodhpur": ["Jodhpur", "Bilara", "Osian"],
  "Rajasthan|||Jodhpur Rural": ["Jodhpur Rural"],
  "Rajasthan|||Karauli": ["Karauli"],
  "Rajasthan|||Khairthal-Tijara": ["Khairthal-Tijara"],
  "Rajasthan|||Kota": ["Kota", "Ramganj Mandi", "Sangod"],
  "Rajasthan|||Kotputli-Behror": ["Kotputli-Behror"],
  "Rajasthan|||Nagaur": ["Nagaur"],
  "Rajasthan|||Neem Ka Thana": ["Neem Ka Thana"],
  "Rajasthan|||Pali": ["Pali"],
  "Rajasthan|||Phalodi": ["Phalodi"],
  "Rajasthan|||Pratapgarh": ["Pratapgarh"],
  "Rajasthan|||Rajsamand": ["Rajsamand"],
  "Rajasthan|||Salumbar": ["Salumbar"],
  "Rajasthan|||Sawai Madhopur": ["Sawai Madhopur"],
  "Rajasthan|||Shahpura": ["Shahpura"],
  "Rajasthan|||Sikar": ["Sikar"],
  "Rajasthan|||Sirohi": ["Sirohi"],
  "Rajasthan|||Tonk": ["Tonk"],
  "Rajasthan|||Udaipur": ["Udaipur", "Gogunda", "Salumbar"],
  "Sikkim|||Gangtok": ["Gangtok"],
  "Sikkim|||Gyalshing": ["Gyalshing"],
  "Sikkim|||Mangan": ["Mangan"],
  "Sikkim|||Namchi": ["Namchi"],
  "Sikkim|||Pakyong": ["Pakyong"],
  "Sikkim|||Soreng": ["Soreng"],
  "Tamil Nadu|||Ariyalur": ["Ariyalur", "Jayankondam", "Sendurai"],
  "Tamil Nadu|||Chengalpattu": ["Chengalpattu", "Tambaram", "Maraimalai Nagar", "Kelambakkam"],
  "Tamil Nadu|||Chennai": ["Chennai", "Ambattur", "Avadi", "Guindy"],
  "Tamil Nadu|||Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam", "Sulur", "Annur", "Valparai"],
  "Tamil Nadu|||Cuddalore": ["Cuddalore", "Chidambaram", "Panruti", "Neyveli", "Virudhachalam"],
  "Tamil Nadu|||Dharmapuri": ["Dharmapuri", "Harur", "Pennagaram", "Palacode"],
  "Tamil Nadu|||Dindigul": ["Dindigul", "Palani", "Kodaikanal", "Oddanchatram", "Vedasandur"],
  "Tamil Nadu|||Erode": ["Erode", "Bhavani", "Gobichettipalayam", "Sathyamangalam", "Perundurai"],
  "Tamil Nadu|||Kallakurichi": ["Kallakurichi", "Ulundurpet", "Sankarapuram", "Chinnasalem"],
  "Tamil Nadu|||Kancheepuram": ["Kancheepuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
  "Tamil Nadu|||Karur": ["Karur", "Kulithalai", "Aravakurichi"],
  "Tamil Nadu|||Krishnagiri": ["Krishnagiri", "Hosur", "Denkanikottai"],
  "Tamil Nadu|||Madurai": ["Madurai", "Melur", "Thirumangalam", "Usilampatti"],
  "Tamil Nadu|||Mayiladuthurai": ["Mayiladuthurai", "Sirkazhi", "Poompuhar"],
  "Tamil Nadu|||Nagapattinam": ["Nagapattinam", "Mayiladuthurai", "Vedaranyam"],
  "Tamil Nadu|||Namakkal": ["Namakkal", "Tiruchengode", "Rasipuram", "Paramathi Velur"],
  "Tamil Nadu|||Nilgiris": ["Nilgiris"],
  "Tamil Nadu|||Perambalur": ["Perambalur", "Veppanthattai", "Kunnam"],
  "Tamil Nadu|||Pudukkottai": ["Pudukkottai", "Aranthangi", "Alangudi", "Illuppur"],
  "Tamil Nadu|||Ramanathapuram": ["Ramanathapuram", "Paramakudi", "Rameswaram", "Kamuthi"],
  "Tamil Nadu|||Ranipet": ["Ranipet", "Arcot", "Walajah", "Arakkonam"],
  "Tamil Nadu|||Salem": ["Salem", "Mettur", "Attur", "Edappadi", "Omalur", "Sankari"],
  "Tamil Nadu|||Sivaganga": ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai"],
  "Tamil Nadu|||Tenkasi": ["Tenkasi", "Sankarankovil", "Courtallam", "Shenkottai"],
  "Tamil Nadu|||Thanjavur": ["Thanjavur", "Kumbakonam", "Pattukkottai", "Orathanadu"],
  "Tamil Nadu|||Theni": ["Theni", "Periyakulam", "Bodinayakanur", "Cumbum", "Uthamapalayam", "Andipatti"],
  "Tamil Nadu|||Thoothukudi": ["Thoothukudi"],
  "Tamil Nadu|||Tiruchirappalli": ["Tiruchirappalli", "Srirangam", "Manapparai", "Musiri", "Thuraiyur", "Lalgudi"],
  "Tamil Nadu|||Tirunelveli": ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Tenkasi"],
  "Tamil Nadu|||Tirupathur": ["Tirupathur", "Vaniyambadi", "Ambur"],
  "Tamil Nadu|||Tiruppur": ["Tiruppur", "Avinashi", "Palladam", "Dharapuram", "Kangeyam", "Udumalpet"],
  "Tamil Nadu|||Tiruvallur": ["Tiruvallur", "Avadi", "Ponneri", "Gummidipoondi", "Tiruttani"],
  "Tamil Nadu|||Tiruvannamalai": ["Tiruvannamalai", "Arani", "Cheyyar", "Polur"],
  "Tamil Nadu|||Tiruvarur": ["Tiruvarur", "Mannargudi", "Thiruthuraipoondi", "Nannilam"],
  "Tamil Nadu|||Vellore": ["Vellore", "Katpadi", "Gudiyatham", "Pernambut"],
  "Tamil Nadu|||Viluppuram": ["Viluppuram"],
  "Tamil Nadu|||Virudhunagar": ["Virudhunagar", "Sivakasi", "Rajapalayam", "Aruppukkottai", "Srivilliputhur"],
  "Telangana|||Adilabad": ["Adilabad"],
  "Telangana|||Bhadradri Kothagudem": ["Bhadradri Kothagudem"],
  "Telangana|||Hanamkonda": ["Hanamkonda"],
  "Telangana|||Hyderabad": ["Hyderabad", "Secunderabad"],
  "Telangana|||Jagtial": ["Jagtial"],
  "Telangana|||Jangaon": ["Jangaon"],
  "Telangana|||Jayashankar Bhupalpally": ["Jayashankar Bhupalpally"],
  "Telangana|||Jogulamba Gadwal": ["Jogulamba Gadwal"],
  "Telangana|||Kamareddy": ["Kamareddy"],
  "Telangana|||Karimnagar": ["Karimnagar", "Huzurabad"],
  "Telangana|||Khammam": ["Khammam", "Kothagudem"],
  "Telangana|||Kumuram Bheem Asifabad": ["Kumuram Bheem Asifabad"],
  "Telangana|||Mahabubabad": ["Mahabubabad"],
  "Telangana|||Mahabubnagar": ["Mahabubnagar"],
  "Telangana|||Mancherial": ["Mancherial"],
  "Telangana|||Medak": ["Medak"],
  "Telangana|||Medchal-Malkajgiri": ["Medchal", "Kompally", "Malkajgiri"],
  "Telangana|||Mulugu": ["Mulugu"],
  "Telangana|||Nagarkurnool": ["Nagarkurnool"],
  "Telangana|||Nalgonda": ["Nalgonda", "Miryalaguda", "Devarakonda"],
  "Telangana|||Narayanpet": ["Narayanpet"],
  "Telangana|||Nirmal": ["Nirmal"],
  "Telangana|||Nizamabad": ["Nizamabad", "Bodhan", "Armoor"],
  "Telangana|||Peddapalli": ["Peddapalli"],
  "Telangana|||Rajanna Sircilla": ["Rajanna Sircilla"],
  "Telangana|||Rangareddy": ["Hyderabad", "LB Nagar", "Shamshabad"],
  "Telangana|||Sangareddy": ["Sangareddy"],
  "Telangana|||Siddipet": ["Siddipet"],
  "Telangana|||Suryapet": ["Suryapet"],
  "Telangana|||Vikarabad": ["Vikarabad"],
  "Telangana|||Wanaparthy": ["Wanaparthy"],
  "Telangana|||Warangal": ["Warangal", "Hanamkonda", "Kazipet"],
  "Telangana|||Yadadri Bhuvanagiri": ["Yadadri Bhuvanagiri"],
  "Tripura|||Dhalai": ["Dhalai"],
  "Tripura|||Gomati": ["Gomati"],
  "Tripura|||Khowai": ["Khowai"],
  "Tripura|||North Tripura": ["North Tripura"],
  "Tripura|||Sepahijala": ["Sepahijala"],
  "Tripura|||South Tripura": ["South Tripura"],
  "Tripura|||Unakoti": ["Unakoti"],
  "Tripura|||West Tripura": ["West Tripura"],
  "Uttar Pradesh|||Agra": ["Agra", "Fatehabad", "Etmadpur"],
  "Uttar Pradesh|||Aligarh": ["Aligarh"],
  "Uttar Pradesh|||Ambedkar Nagar": ["Ambedkar Nagar"],
  "Uttar Pradesh|||Amethi": ["Amethi"],
  "Uttar Pradesh|||Amroha": ["Amroha"],
  "Uttar Pradesh|||Auraiya": ["Auraiya"],
  "Uttar Pradesh|||Ayodhya": ["Ayodhya"],
  "Uttar Pradesh|||Azamgarh": ["Azamgarh"],
  "Uttar Pradesh|||Baghpat": ["Baghpat"],
  "Uttar Pradesh|||Bahraich": ["Bahraich"],
  "Uttar Pradesh|||Ballia": ["Ballia"],
  "Uttar Pradesh|||Balrampur": ["Balrampur"],
  "Uttar Pradesh|||Banda": ["Banda"],
  "Uttar Pradesh|||Barabanki": ["Barabanki"],
  "Uttar Pradesh|||Bareilly": ["Bareilly"],
  "Uttar Pradesh|||Basti": ["Basti"],
  "Uttar Pradesh|||Bhadohi": ["Bhadohi"],
  "Uttar Pradesh|||Bijnor": ["Bijnor"],
  "Uttar Pradesh|||Budaun": ["Budaun"],
  "Uttar Pradesh|||Bulandshahr": ["Bulandshahr"],
  "Uttar Pradesh|||Chandauli": ["Chandauli"],
  "Uttar Pradesh|||Chitrakoot": ["Chitrakoot"],
  "Uttar Pradesh|||Deoria": ["Deoria"],
  "Uttar Pradesh|||Etah": ["Etah"],
  "Uttar Pradesh|||Etawah": ["Etawah"],
  "Uttar Pradesh|||Farrukhabad": ["Farrukhabad"],
  "Uttar Pradesh|||Fatehpur": ["Fatehpur"],
  "Uttar Pradesh|||Firozabad": ["Firozabad"],
  "Uttar Pradesh|||Gautam Buddha Nagar": ["Noida", "Greater Noida", "Dadri"],
  "Uttar Pradesh|||Ghaziabad": ["Ghaziabad", "Loni", "Modinagar"],
  "Uttar Pradesh|||Ghazipur": ["Ghazipur"],
  "Uttar Pradesh|||Gonda": ["Gonda"],
  "Uttar Pradesh|||Gorakhpur": ["Gorakhpur", "Sahjanwa", "Pipraich"],
  "Uttar Pradesh|||Hamirpur": ["Hamirpur"],
  "Uttar Pradesh|||Hapur": ["Hapur"],
  "Uttar Pradesh|||Hardoi": ["Hardoi"],
  "Uttar Pradesh|||Hathras": ["Hathras"],
  "Uttar Pradesh|||Jalaun": ["Jalaun"],
  "Uttar Pradesh|||Jaunpur": ["Jaunpur", "Shahganj", "Machhlishahr"],
  "Uttar Pradesh|||Jhansi": ["Jhansi"],
  "Uttar Pradesh|||Kannauj": ["Kannauj"],
  "Uttar Pradesh|||Kanpur Dehat": ["Kanpur Dehat"],
  "Uttar Pradesh|||Kanpur Nagar": ["Kanpur", "Bilhaur"],
  "Uttar Pradesh|||Kasganj": ["Kasganj"],
  "Uttar Pradesh|||Kaushambi": ["Kaushambi"],
  "Uttar Pradesh|||Kheri": ["Kheri"],
  "Uttar Pradesh|||Kushinagar": ["Kushinagar"],
  "Uttar Pradesh|||Lalitpur": ["Lalitpur"],
  "Uttar Pradesh|||Lucknow": ["Lucknow", "Malihabad", "Mohan"],
  "Uttar Pradesh|||Maharajganj": ["Maharajganj"],
  "Uttar Pradesh|||Mahoba": ["Mahoba"],
  "Uttar Pradesh|||Mainpuri": ["Mainpuri"],
  "Uttar Pradesh|||Mathura": ["Mathura"],
  "Uttar Pradesh|||Mau": ["Mau"],
  "Uttar Pradesh|||Meerut": ["Meerut", "Mawana", "Sardhana"],
  "Uttar Pradesh|||Mirzapur": ["Mirzapur"],
  "Uttar Pradesh|||Moradabad": ["Moradabad"],
  "Uttar Pradesh|||Muzaffarnagar": ["Muzaffarnagar"],
  "Uttar Pradesh|||Pilibhit": ["Pilibhit"],
  "Uttar Pradesh|||Pratapgarh": ["Pratapgarh"],
  "Uttar Pradesh|||Prayagraj": ["Prayagraj", "Phulpur", "Koraon"],
  "Uttar Pradesh|||Raebareli": ["Raebareli"],
  "Uttar Pradesh|||Rampur": ["Rampur"],
  "Uttar Pradesh|||Saharanpur": ["Saharanpur"],
  "Uttar Pradesh|||Sambhal": ["Sambhal"],
  "Uttar Pradesh|||Sant Kabir Nagar": ["Sant Kabir Nagar"],
  "Uttar Pradesh|||Shahjahanpur": ["Shahjahanpur"],
  "Uttar Pradesh|||Shamli": ["Shamli"],
  "Uttar Pradesh|||Shravasti": ["Shravasti"],
  "Uttar Pradesh|||Siddharthnagar": ["Siddharthnagar"],
  "Uttar Pradesh|||Sitapur": ["Sitapur"],
  "Uttar Pradesh|||Sonbhadra": ["Sonbhadra"],
  "Uttar Pradesh|||Sultanpur": ["Sultanpur"],
  "Uttar Pradesh|||Unnao": ["Unnao"],
  "Uttar Pradesh|||Varanasi": ["Varanasi", "Ramnagar", "Pindra"],
  "Uttarakhand|||Almora": ["Almora"],
  "Uttarakhand|||Bageshwar": ["Bageshwar"],
  "Uttarakhand|||Chamoli": ["Chamoli"],
  "Uttarakhand|||Champawat": ["Champawat"],
  "Uttarakhand|||Dehradun": ["Dehradun", "Rishikesh", "Mussoorie"],
  "Uttarakhand|||Haridwar": ["Haridwar", "Roorkee", "Jwalapur"],
  "Uttarakhand|||Nainital": ["Nainital", "Haldwani", "Ramnagar"],
  "Uttarakhand|||Pauri Garhwal": ["Pauri", "Kotdwar", "Srinagar"],
  "Uttarakhand|||Pithoragarh": ["Pithoragarh"],
  "Uttarakhand|||Rudraprayag": ["Rudraprayag"],
  "Uttarakhand|||Tehri Garhwal": ["Tehri Garhwal"],
  "Uttarakhand|||Udham Singh Nagar": ["Rudrapur", "Kashipur", "Kichha"],
  "Uttarakhand|||Uttarkashi": ["Uttarkashi"],
  "West Bengal|||Alipurduar": ["Alipurduar"],
  "West Bengal|||Bankura": ["Bankura"],
  "West Bengal|||Paschim Bardhaman": ["Paschim Bardhaman"],
  "West Bengal|||Purba Bardhaman": ["Purba Bardhaman"],
  "West Bengal|||Birbhum": ["Birbhum"],
  "West Bengal|||Cooch Behar": ["Cooch Behar"],
  "West Bengal|||Dakshin Dinajpur": ["Dakshin Dinajpur"],
  "West Bengal|||Darjeeling": ["Darjeeling", "Siliguri", "Kurseong"],
  "West Bengal|||Hooghly": ["Chinsurah", "Serampore", "Chandannagar"],
  "West Bengal|||Howrah": ["Howrah", "Uluberia"],
  "West Bengal|||Jalpaiguri": ["Jalpaiguri"],
  "West Bengal|||Jhargram": ["Jhargram"],
  "West Bengal|||Kalimpong": ["Kalimpong"],
  "West Bengal|||Kolkata": ["Kolkata"],
  "West Bengal|||Maldah": ["Maldah"],
  "West Bengal|||Murshidabad": ["Murshidabad"],
  "West Bengal|||Nadia": ["Nadia"],
  "West Bengal|||North 24 Parganas": ["Barasat", "Barrackpore", "Bongaon"],
  "West Bengal|||South 24 Parganas": ["Alipore", "Baruipur", "Diamond Harbour"],
  "West Bengal|||Paschim Medinipur": ["Paschim Medinipur"],
  "West Bengal|||Purba Medinipur": ["Purba Medinipur"],
  "West Bengal|||Uttar Dinajpur": ["Uttar Dinajpur"],
  "Andaman and Nicobar Islands|||Nicobars": ["Car Nicobar", "Campbell Bay"],
  "Andaman and Nicobar Islands|||North and Middle Andaman": ["Mayabunder", "Rangat"],
  "Andaman and Nicobar Islands|||South Andaman": ["Port Blair", "Bamboo Flat"],
  "Chandigarh|||Chandigarh": ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu|||Dadra and Nagar Haveli": ["Silvassa"],
  "Dadra and Nagar Haveli and Daman and Diu|||Daman": ["Daman"],
  "Dadra and Nagar Haveli and Daman and Diu|||Diu": ["Diu"],
  "Delhi|||Central Delhi": ["Central Delhi"],
  "Delhi|||East Delhi": ["East Delhi"],
  "Delhi|||New Delhi": ["New Delhi"],
  "Delhi|||North Delhi": ["North Delhi"],
  "Delhi|||North East Delhi": ["North East Delhi"],
  "Delhi|||North West Delhi": ["North West Delhi"],
  "Delhi|||Shahdara": ["Shahdara"],
  "Delhi|||South Delhi": ["South Delhi"],
  "Delhi|||South East Delhi": ["South East Delhi"],
  "Delhi|||South West Delhi": ["South West Delhi"],
  "Delhi|||West Delhi": ["West Delhi"],
  "Jammu and Kashmir|||Anantnag": ["Anantnag", "Bijbehara", "Pahalgam"],
  "Jammu and Kashmir|||Bandipora": ["Bandipora"],
  "Jammu and Kashmir|||Baramulla": ["Baramulla", "Sopore", "Uri"],
  "Jammu and Kashmir|||Budgam": ["Budgam"],
  "Jammu and Kashmir|||Doda": ["Doda"],
  "Jammu and Kashmir|||Ganderbal": ["Ganderbal"],
  "Jammu and Kashmir|||Jammu": ["Jammu", "Akhnoor", "Bishnah"],
  "Jammu and Kashmir|||Kathua": ["Kathua", "Hiranagar"],
  "Jammu and Kashmir|||Kishtwar": ["Kishtwar"],
  "Jammu and Kashmir|||Kulgam": ["Kulgam"],
  "Jammu and Kashmir|||Kupwara": ["Kupwara"],
  "Jammu and Kashmir|||Poonch": ["Poonch"],
  "Jammu and Kashmir|||Pulwama": ["Pulwama"],
  "Jammu and Kashmir|||Rajouri": ["Rajouri"],
  "Jammu and Kashmir|||Ramban": ["Ramban"],
  "Jammu and Kashmir|||Reasi": ["Reasi"],
  "Jammu and Kashmir|||Samba": ["Samba"],
  "Jammu and Kashmir|||Shopian": ["Shopian"],
  "Jammu and Kashmir|||Srinagar": ["Srinagar", "Ganderbal"],
  "Jammu and Kashmir|||Udhampur": ["Udhampur", "Ramnagar"],
  "Ladakh|||Kargil": ["Kargil", "Drass"],
  "Ladakh|||Leh": ["Leh"],
  "Lakshadweep|||Lakshadweep": ["Kavaratti", "Agatti", "Andrott"],
  "Puducherry|||Karaikal": ["Karaikal"],
  "Puducherry|||Mahe": ["Mahe"],
  "Puducherry|||Puducherry": ["Puducherry"],
  "Puducherry|||Yanam": ["Yanam"]
};

export function getDistricts(state) {
  return DISTRICTS_BY_STATE[state] || [];
}

export function getLocalities(district, state) {
  if (state) return getLocalitiesByStateAndDistrict(state, district);
  return LOCALITIES_BY_DISTRICT[district] || [];
}

export function getLocalitiesByStateAndDistrict(state, district) {
  if (!state || !district) return [];
  return LOCALITIES_BY_STATE_AND_DISTRICT[`${state}|||${district}`] || [];
}
